### ISSUE TITLE
How to configure to generate log if there is already a release 

### ISSUE THREAD

**Issue by josesimoes** [mikepenz/release-changelog-builder-action#1000]
Hi,

I'm getting familiar with this action to add it to [.NET nanoFramework](https://github.com/nanoframework) repositories.

Pretty impressed with the performance, how flexible the configuration is and the docs are a complete joy to use. Congrats on a very professional work! 👏🏻 👏🏻 👏🏻 

I have a question:  how to properly configure the action when there is already an github release in draft?
On our pipelines the releases are drafted by an AZDO pipeline. Please take a look at the action here:
https://github.com/nanoframework/nf-Visual-Studio-extension/blob/develop/.github/workflows/generate-changelog-vs2022.yml

Thanks!

**Comment by mikepenz** [comment]
Hi @josesimoes 

Thank you very much for the kind feedback. 

This action itself does not contain release creation or updating the release within GitHub. It solely focuses on the aspect of creating the changelog for you (the way you need it) 


For the creation of the GitHub release I often used: https://github.com/marketplace/actions/gh-release

**Comment by josesimoes** [comment]
Hey @mikepenz,

Thanks for the quick reply. I'm afraid I have failed to properly explain my question... 😅 
I'm not looking into using this action to create releases, rather to generate the change log.

From my testing I got under the impression that without any particular config, it would search for the latest tag/release and it generates a change log from that point to the latest commit. 

Considering that the workflow we're using on our pipelines is creating a release tag on AZDO, when it get's to run the changelog action, there are already 2 tags in git history: the latest one (just created) and the N-1 one. 
On the yaml above, I had to add an extra step before running `release-changelog-builder-action` in order to find out what is that N-1 tag and pass it to the action.

My question was about if there is a way of using `release-changelog-builder-action` in such use case, without having to pass that N-1 to `fromTag`. Kind of having it figure out "hey there is a tag here, let me find the previous one and generate the change log between them".

Hope I've managed to explain this better now...

**Comment by mikepenz** [comment]
@josesimoes thank you very much for explaining it further. I absolutely misunderstood completely. Apologies. 

And yes, as you correctly noted, without any particular config the action would search for latest tag/release and get the release prior to that. 

This works in following conditions:

[toTag](https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/tags.ts#L177-L204):
- it will prioritise manually passed tag via the config
- if non provided it will check the `github.ref` and see if a `refs/tags/` reference was done (e.g. build triggered by tag push)
- if not found, if more than 1 tag if retrieved via the [GitHub API](https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/tags.ts#L29) - the latest is used (please note that this takes tag transformer config and filtering into consideration)
- last try - use the `git cli` to retrieve it

[fromTag](https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/tags.ts#L100-L123)
- it will prioritise manually passed tag via the config
- if non provided it will check the tag prior to the `toTag` (as returned by the GitHub API) (as noted above filter and transform apply) 
- if not found, the `git cli` is used to retrieve it. 


Things which may affect this - by default `semVer` sorting is done on tags, if they are not `semVer` they may be dropped. 

Looking at the repo, it looks you do not use `semVer` but some mixed versioning scheme. 

Alternative a fallback sorting logic could be `string` sorting - but that may be error prone for the versioning scheme you use (string sorting works usually great for `calVer`)

Do you have the logs for the build where you did not provide `fromTag`? That may give some further clarity on this behaviour.

**Comment by josesimoes** [comment]
Glad that we are on the same page now! 😁 and thank you for looking into this.

Logs for all my attempts are [here](https://github.com/nanoframework/nf-Visual-Studio-extension/actions).
Thanks for detailing the logic on the "find tags". I understand it better now.

And yes, the fact that't not using semVer doesn't help either. In this particular repo (which is the only one with this tagging style) it's because this is a VS extension and it's been evolving since VS2017 and it's using a common code base.
Currently we're actively maintaining VS2019 and VS2022, that's the reason why you see there v2017.n.n and v2022.n.n on the latest tag history.

Most releases are for both versions, but every now and then there is one that only targeting one of them. Therefore there is the need to rely on that search pattern to find out the N and N-1 tags for each VS version.

Considering all this and your explanation, I'm thinking that this is probably already setup/config in the most optimal way... unless you have any advice to offer regarding this.

**Comment by mikepenz** [comment]
Will need to check out the logs some, and think more about it. 

The pure `CLI` approach wouldn't work either, given that this one does not go through the transform nor filter logic. And your usecase does require tags to be filtered by the prefix (`v2022.*`) 

For now your approach seems to definitely be a great choice.

**Comment by mikepenz** [comment]
Thank you once again for the detailed description. As we settled in the last comment that this is currently set up in the best way I'll close this ticket. 

At this time I believe the offered variants of filtering and different offers to define the range and included PRs is good for most situations. 

Happy to have further discussions if there are more reports of a different solution being required. 

Kind regards, Mike
