### ISSUE TITLE
push_git_tags in Fastlane don't trigger CI

### ISSUE THREAD

**Issue by PhongHuynh93** [mikepenz/release-changelog-builder-action#1003]
I used this changelog CI:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/15118915/211332457-c55f311b-736a-484a-bcab-1d3346e34a4e.png">

I used fastlane to add a new git tag (https://docs.fastlane.tools/actions/add_git_tag/) and push it (https://docs.fastlane.tools/actions/push_git_tags/). But it didn't trigger the changelog CI. Is it intentional? How do I make it work?

**Comment by mikepenz** [comment]
@PhongHuynh93 that is more of a question towards GitHub actions itself, and not to this action. 
As your question asks regarding GitHub action triggers (not the execution of this action offered) 


Some questions which may help:
- Was the tag potentially not matching your pattern? 
```
on:
  push:
    tags:
      - '*'
```
- What type of token was fastlane using? The CI token? Or was it using a PAT?

**Comment by PhongHuynh93** [comment]
Fastlane has already pushed the tag 1.0.6 successfully, I think it matches my pattern `[123].[0-9]+.[0-9]+` 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/15118915/211338495-e5ce5235-836e-40e3-8db2-ae497ffb5466.png">

I used this doc to integrate fastlane into my Android project https://docs.fastlane.tools/getting-started/android/setup/ . It didn't mention any token :( I really don't know what type of token it is using.
