### ISSUE TITLE
Help: conditional formatting in the template (hiding "Uncategorized" if there are no uncategorized PRs)

### ISSUE THREAD

**Issue by mikeage** [mikepenz/release-changelog-builder-action#1015]
Hi,

I'm wondering if I can get some advice on what's the best way to handle my situation. I have quite a few PRs that don't have labels, and for whatever reason, I don't want to make labels mandatory. I nevertheless want to include them in the PR.

I added a configuration json with something similar to this suggestion:

```
"template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>"
```

But I'd like to make sure that the "Uncategorized" section doesn't show up at all if `${{UNCATEGORIZED}}` is empty (or perhaps alternatively, if `${{UNCATEGORIZED_COUNT}}` is zero). Is there an easy way to do this?

Alternatively, is there a way that I can add a "fallback" category, perhaps using some type of rules and the duplicate filter, to catch them, as these are automatically suppressed if empty. Something along the lines of (and this won't work as-is...):

```json
    "categories": [
      ...
      {
        "title": "## Uncategorized",
        "labels": [], # Maybe?
        "exclude_labels": ["all", "of", "my", "other", "labels"],   # Or is this done with a duplicate filter?
        "rules": [
          {
            "something": "maybe?"
          }
        ]
      }
```

**Comment by mikepenz** [comment]
Good day @mikeage 

Yes, it is possible to have a category which collects all uncategorized PRs. Your thought on the fallback category is already very close to what's possible. 

See a test case here:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/configs_test/configuration_uncategorized_category.json#L7-L10

It's worth noting, if it is part of the normal `CHANGELOG` you won't be able to have it as a summary section like it is right now

**Comment by mikeage** [comment]
perfect, thanks for the quick response!
