### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by fhopfensperger** [mikepenz/release-changelog-builder-action#1023]
First of all, thank you for all the hard work you do here.

I have a suggestion, could you maybe clean up the current "remote" branches a bit? Currently there are a lot of "stale" branches (around 150) where the PR has already been merged, but the branch has not been deleted. 
Since we are using a GitHub Enterprise version, we need to sync the repo/action with all the "dead" branches with our GHE instance.

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/9072240/219020247-b1358548-6b9d-4a47-b1fd-dff73949e004.png">

Thank you and keep up the good work!

**Comment by mikepenz** [comment]
Good day @fhopfensperger 

pruned a good amount of them. So there are now only 17 left.

Hope that helps

**Comment by fhopfensperger** [comment]
thank you!
