### ISSUE TITLE
[Question] Can we use a different style label for label extractor and category?

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#1035]
Hi @mikepenz,

Greetings.

I was wondering if we can set a different label for the category and the label extractor, e.g.
```yml
{
    "categories": [
        {
            "title": "## 🚀 Features",
            "labels": [
                "feat"
            ],
            "exhaustive": true
        },
        {
            "title": "## 🐛 Fixes",
            "labels": [
                "fix"
            ],
            "exhaustive": true
    ],
    "label_extractor": [
        {
            "pattern": ".*(feat\\(${{ backend }}\\)).*",
            "target": "$1",
            "on_property": "title"
        },
        {
            "pattern": ".*(fix\\(${{ backend }}\\)).*",
            "target": "$1",
            "on_property": "title"
        }
    ]
}
```

In this case I will filter PRs based on a scope: backend, but they will be categorized in with a label: feat and fix only.

**Comment by mikepenz** [comment]
@dtcMLOps to repeat I understand i properly. Your goal is to build a changelog only for items which were identified to be scoped by backend? 

Theoretically the idea is a good one. I'd actually suggest to use the newer `rules` you can provide on `categories`

```
 "rules": [
          {
            "pattern": "open",
            "on_property": "status",
            "flags": "gu"
          }
        ]
```

Which will include all PRs in this particular category if they match that particular rule. 

This is a bit simpler as it uses the following: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/regexUtils.ts#LL32C34-L32C34 to `test` a regex. 

(so as long as the pattern test returns `true` the PR will be included) 

And the nice part is you can do it also on the `title` property.

**Comment by mikepenz** [comment]
E.g.:
<img width="653" alt="Screenshot 2023-02-28 at 18 25 06" src="https://user-images.githubusercontent.com/1476232/221930095-e39a2833-4dcb-40ed-ad64-0b5de60e4120.png">

**Comment by mikepenz** [comment]
@dtcMLOps I see this ticket being closed now. I assume you found the answer?

**Comment by mikepenz** [comment]
Thank you for the response. 

Glad that this works. 

I saw the new ticket, I may not be able to answer it today or tomorrow, busy days. I'll try to come to it as soon as possible.
