### ISSUE TITLE
fails to create changelog with: ⚠️ No pull requests found

### ISSUE THREAD

**Issue by plastikfan** [mikepenz/release-changelog-builder-action#1044]
So I am using the PR model in my test [repo, lucretia](https://github.com/snivilised/lucretia). My release process is:

- create a local release branch, (eg: __release/0.1.5__)
- make release specific changes
- tag this release
- then push this release branch with the tag (eg: __git push --set-upstream --follow-tags origin release/0.1.5__)
- this triggers my changelog workflow containing ___release-changelog-builder-action___

There are commits with either feature/fix labels since the last tag. I also make sure that the PRs used to merge them back into master are also labelled with the same label. I am also using a [config file](https://github.com/snivilised/lucretia/blob/master/config/changelog.config.json) as opposed to specifying the config inline in the [yaml](https://github.com/snivilised/lucretia/blob/master/.github/workflows/changelog-workflow.yml).

However, a possibly essential point to note is that those commits are merged with the ___Rebase and Merge___ option. I don't know if this is significant or not, but I mention it because you asked about this is this other closed [issue (939)](https://github.com/mikepenz/release-changelog-builder-action/issues/939).

When I then look at the github action log for the [workflow](https://github.com/snivilised/lucretia/actions/runs/4363046503), which shows "⚠️ No pull requests found"

How do I fix this?

Thanks.

**Comment by plastikfan** [comment]
I found the problem, it was the incorrect value of the base branch in the config. By default it contains "dev",, but my repo doesn't use a dev branch, so I canged to "master" and now it's working.

**Comment by mikepenz** [comment]
@plastikfan most of the values you configure in your config are not required to be defined. 

https://github.com/snivilised/lucretia/blob/master/config/changelog.config.json#L50-L90

The README outlines sample with every element filled, but you can simplify it substantially to:

```
{
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": [
        "feature"
      ]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix"
      ]
    },
    {
      "title": "## 🧪 Tests",
      "labels": [
        "test"
      ]
    },
    {
      "title": "## 🧪 Tests and some ✨ Magic",
      "labels": [
        "test",
        "magic"
      ],
      "exclude_labels": [
        "no-magic"
      ],
      "exhaustive": true,
      "empty_content": "- no matching PRs",
      "rules": [
        {
          "pattern": "open",
          "on_property": "status",
          "flags": "gu"
        }
      ]
    }
  ]
}
```

**Comment by plastikfan** [comment]
Ok great thanks. I'm also getting confused abouth the labels, eg the "fix" label as you show it here, shouldn't that be "bug", because that is the actual label you get by default from github?

And yeah, I'm gonna complyetely strip down the config. I just copied the documented full config so I could see all the possible settings.
