### ISSUE TITLE
{latest-release} ?

### ISSUE THREAD

**Issue by Fr-Dae** [mikepenz/release-changelog-builder-action#1054]
build_changelog
Unable to resolve action `mikepenz/release-changelog-builder-action@{latest-release}`, unable to find version `{latest-release}`

**Comment by mikepenz** [comment]
`{latest-release}` is a placeholder. Find the latest releases here please: https://github.com/mikepenz/release-changelog-builder-action/releases

**Comment by Fr-Dae** [comment]
i know, but it's from your script 
and you write nowhere the user need edit it

**Comment by Niek** [comment]
I was confused by this too, `@v6` would have been clearer.
