### ISSUE TITLE
Update to remove set-output and replace with GITHUB_OUTPUT

### ISSUE THREAD

**Issue by thejeff77** [mikepenz/release-changelog-builder-action#1058]
set-output is deprecated, and running the action gives a lot of warnings. 

This action is great, would be cool if this was fixed before that feature is removed.

Thanks!

**Comment by mikepenz** [comment]
@thejeff77 which version are you using?

The latest version should not show those warnings (and I don't see these warnings using it in various projects myself)

**Comment by mikepenz** [comment]
Not sure which tests you are referencing to? Could you please link me to it?

**Comment by thejeff77** [comment]
Eg running: `npm test -- releaseNotes.test.ts` on the command line shows a lot of these.

**Comment by mikepenz** [comment]
Finally had a time to look. Those are the log messages of the tests only, and it's not actually doing the deprecated action. 

Thank you for the report.
