### ISSUE TITLE
[Question] How can I trigger the example if my project dont have tag or release?

### ISSUE THREAD

**Issue by julioNico** [mikepenz/release-changelog-builder-action#1066]
Hello, sorry about my question, but i am learing about github actions...

I am trying to run, **using git push**,  the example below, but dont trigger... **My project dont have tag or release yet**, this action don`t create a new tag and release?

The example:

> name: 'CI'
> on:
>   push:
>     tags:
>       - '*'
> 
> jobs:
>   release:
>     if: startsWith(github.ref, 'refs/tags/')
>     runs-on: ubuntu-latest
>     steps:
>       - name: Build Changelog
>         id: github_release
>         uses: mikepenz/release-changelog-builder-action@v3
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>       - name: Create Release
>         uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
>         with:
>           body: ${{steps.github_release.outputs.changelog}}

          
          
Thanks

**Comment by mikepenz** [comment]
@julioNico this action does not create the tag or release no. it's sole purpose is to provide functionality to create the release notes. 

If you don't have tags, you can also change the trigger, please be aware that if you don't trigger it via a tag, that the action will need additional information on the `toTag` you expect to create the release notes for

**Comment by julioNico** [comment]
Ok, I got it! thank you so much, @mikepenz.
