### ISSUE TITLE
How are dates that determine the PR's set

### ISSUE THREAD

**Issue by JustinFrostF5** [mikepenz/release-changelog-builder-action#1089]
I have been using this action for quite a while now, many thanks for the development and maintenance.

Recently the dates it is using to fetch PR's do not match the from and to tags:

Comparing JeminiDev/Jemini-App - 'v29.1.0-SNAPSHOT-10...v29.1.0-SNAPSHOT-11'
  ℹ️ Found 31 commits from the GitHub API for ...
  ℹ️ Fetching PRs between dates 2023-04-14T06:38:03.000Z to 2023-05-02T00:17:41.000Z for ...

The toTag date is correct, how is the fromTag timestamp determined ?
v29.1.0-SNAPSHOT-10 was tagged yesterday and it using 2023-04-14T06:38:03.000Z

Thanks.

**Comment by mikepenz** [comment]
@JustinFrostF5 the `dates` you see are unrelated to the `toTag` and `fromTag` dates, given PRs may be created prior to the `fromTag` to exist. 

Let's say you start working on a huge feature on the 1st of January.
While that feature and PR is being worked on, minor releases are made (e.g. tag1, tag2) 

Let's assume the huge feature is merged (however not yet included in a release)
Let's say you release `tag3` on 1st of March. (without huge feature)
Now you release `tag4` - which practically was only created outside of the bounds of `from` to `toTag` range.

Instead the `dates` are retrieved from first to last commit within the identified range: 
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/releaseNotes.ts#L103-L113

with a `max` of the configured `max_back_track_time_days`

**Comment by JustinFrostF5** [comment]
@mikepenz Thanks for the quick reply.  
Your information was helpful and I have discovered my tags where created using the incorrect SHA.

Thanks for your help.
