### ISSUE TITLE
Unexpected results from using label_extractor

### ISSUE THREAD

**Issue by mrowles** [mikepenz/release-changelog-builder-action#1172]
First and foremost, thanks for this great tool, appreciate the work.

I just want to use either the title or the branch of the PR's for the release notes. If the labels HAVE to be utilised, then that is also fine, but prefer not to (I want to keep the logic to within Git itself).

I've followed the examples and scoured through the issues but all of my PR's get put into 'Uncategorised'.

The branches I use are generally in the format `feat|fix|chore: some task` or `feat|fix|chore(auth): some auth task`. I believe that I am missing something small, but I cannot for the life of me make sense of it.

My config is below:

```
{
  "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": [
        "feat",
        "feature"
      ],
      "exhaustive": true
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix",
        "bug"
      ],
      "exhaustive": true
    },
    {
      "title": "## 🛠️ Chores",
      "labels": [
        "chore"
      ],
      "exhaustive": true
    },
    {
      "title": "## 🛠️ Dependencies",
      "labels": [
        "deps"
      ],
      "exhaustive": true
    }
  ],
  "label_extractor": [
    {
      "pattern": "^([\\w\\-]+)",
      "target": "$1",
      "on_property": "branch"
    }
  ]
}
```

Note: I have also tried this specific regex: `feat(?:\(.*\)):|feat:`

Whatever conclusion comes out of this, I would highly recommend adding it as another example because branch and title extraction would be a heavy use case vs labels I'm going to guess.

**Comment by mikepenz** [comment]
Thank you very much @mrowles for the kind words, and the detailed ticket description. 

So there are a few small details resuling in the problem. To test situations like these I always recommend to kick off a `codespace` for this project, and create a test-case (usually I derive from one of the existing ones) to allow for quick testing.
With that done, you can quickly execute the testcase with `npm test -- test.test.ts` 

Find the test-case I created for this ticket here: https://github.com/mikepenz/release-changelog-builder-action/tree/issue/1172

---

The first problem I see is the `category` configuration. Which is defined to be `exhaustive`. This means that the matched PRs do require every label of this category to match. E.g. for feature it would mean the PR requires the `feat` and `feature` label, which is most likely not what you try to achieve. 

The second part is to the approcah of the label extraction. The action supports 2 different methods, 1 is the `replace` regex function from javascript, and the other is `match`. 

For the regex you chose, replace will not result in any results, however `match` will: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L603-L613

So changing the `label_extractor` to `match` will result it to retrieve the first label, which in your povided examples will be `feat`

Applying these changes, will result in it matching the expected category as seen here in the test-case (worth to note that this testcase is set-up to fail :D):
<img width="416" alt="Screenshot 2023-07-25 at 15 29 59" src="https://github.com/mikepenz/release-changelog-builder-action/assets/1476232/7cc5b448-65a5-4ac8-9dcc-c16b1c5d04eb">

**Comment by mrowles** [comment]
@mikepenz Thanks so much mate, it looks to be working a treat. Here is the final code:

```
{
  "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": [
        "feat",
        "feature"
      ]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix",
        "bug"
      ]
    },
    {
      "title": "## 🛠️ Chores",
      "labels": [
        "chore"
      ]
    },
    {
      "title": "## 🛠️ Dependencies",
      "labels": [
        "deps"
      ]
    }
  ],
  "label_extractor": [
    {
      "method": "match",
      "pattern": "^([\\w\\-]+)",
      "target": "$1",
      "on_property": "title"
    }
  ]
}
```

**Comment by mrowles** [comment]
Fixed.

**Comment by mikepenz** [comment]
glad it works for you. 

If you like, please consider contributing a new test case for this case :)
