### ISSUE TITLE
PR cannot be excluded from uncategorized

### ISSUE THREAD

**Issue by sethicis** [mikepenz/release-changelog-builder-action#1178]
## The Issue

This might just be misunderstanding the correct way to use this action to accomplish my goal, but I noticed that if you try to exclude a PR by label from the `Uncategorized` section it will ignore your `exclude_labels`.

### Example

```
// build_changelog_config.json
{
"categories": [
        {
            "title": "## 🚀 Features",
            "labels": ["feature", "story", "feat"],
            "exclude_labels": ["release notes ignore"]
        },
        {
            "title": "## 🐛 Fixes",
            "labels": ["fix", "bug", "bugfix", "hotfix"],
            "exclude_labels": ["release notes ignore"]
        },
        {
            "title": "## 👷 Improvements",
            "labels": ["improvement", "enhancement", "chore", "task", "dependencies"],
            "exclude_labels": ["release notes ignore"]
        },
        {
            "title": "## 📦 Uncategorized",
            "labels": [],
            "exclude_labels": ["release notes ignore"]
        }
    ]
}
```

In the above example the generated release notes would still includes PRs that contain the label "release notes ignore" in the "Uncategorized" section.

## The Goal

Sometimes changes are picked up in the changelog diff that are irrelevant, like the addition of a codeclimate file or updates to dependabot config.  I want to be able to filter out these PRs from the generated release notes to avoid cluttering them up with irrelevant work.

**Comment by mikepenz** [comment]
Thank you very much for the report. You are correct this is currently not covered, however I think it will be a great addition. As such I'll look into getting this included for the new `v4` version.
