### ISSUE TITLE
PR title behaves like command

### ISSUE THREAD

**Issue by kvernon** [mikepenz/release-changelog-builder-action#1193]
Howdy again @mikepenz ,

I've been doing an update using this tool, but along the way it thinks the PR title is a command.

PR Title: `feat: create tag; npm 9; log tags`

```bash

{major:[],features:[- feat: create tag
Unknown command: "9"

To see a list of supported npm commands, run:
  npm help
Error: Process completed with exit code 1.
```

I tried other variations, and the all the titles are behaving like command variations.

For example, I did:

PR Title: `feat: create tag; npm nine; log tags`

```bash

{major:[],features:[- feat: create tag
Unknown command: "nine"

To see a list of supported npm commands, run:
  npm help
Error: Process completed with exit code 1.
```

I'm running 4.

Any ideas?
Kelly

**Comment by mikepenz** [comment]
@kvernon do you have some more logs or some additional details. Or can you point me to the run where this occurred? 

At which stage is this happening?

**Comment by kvernon** [comment]
GM @mikepenz ,

False alarm sir! It looks like it's something from me.

Thanks for asking for more info.

**Comment by mikepenz** [comment]
Phew :D Thanks @kvernon
