### ISSUE TITLE
Changelogs to support Issue number

### ISSUE THREAD

**Issue by parthosa** [mikepenz/release-changelog-builder-action#1197]
Can we have issue number in the change log instead of PR?

**Comment by mikepenz** [comment]
Can you please provide an example of that?

You mean the GitHub issue which references a PR?

**Comment by parthosa** [comment]
Currently, with default config my release body is as follows:

- Test auto release
   - PR: `#1`
- Test auto release 2
   - PR: `#2`

Here, `#1` and `#2` refer to PR numbers. Instead of this, I would like to have them in the format where `#90` and `#80` are issue numbers for these PRs

- Test auto release feature 2 `#90`
- Test auto release feature 5` #80`

**Comment by mikepenz** [comment]
If you have the issue number part of the PR title, or the body, you can already extract this information today, by using custom placeholders. 

This action allows to define custom placeholders which use properties accessible to the PR to extract information. Find more here: https://github.com/mikepenz/release-changelog-builder-action#experimental-

----

However I suppose you are more interested in the action automatically retrieving linked issues from GitHub automatically?

As far as I can see, there is no direct API which returns returns issues associated with a PR. https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request

There is an API which returns a timeline, however that does not clearly list it either. 

- https://api.github.com/repos/mikepenz/multiplatform-markdown-renderer/pulls/62
- https://api.github.com/repos/mikepenz/multiplatform-markdown-renderer/issues/62/timeline
- https://api.github.com/repos/mikepenz/multiplatform-markdown-renderer/issues/62

Based on that I fear this is currently not in scope.

**Comment by parthosa** [comment]
Thanks for the details. I was able to use this action for generating my changelogs and create a release with it. 

Does the `outputFile` create the changelog file and write it to the repo?. I have provided write and read access but I do not see the file generated in my repo.

**Comment by mikepenz** [comment]
That's great to hear. 

the `outputFile` will write the changelog to a file in the respective location. Correct: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/main.ts#L88

It will NOT commit it though, and the file will only be written to the respecitve path. It is up to the respective usecase what to do next with it. E.g. commit it as part of the repo, ....

**Comment by mikepenz** [comment]
As the other question of this ticket is answered: https://github.com/mikepenz/release-changelog-builder-action/issues/1197#issuecomment-1666539233 (unfortunately it seems not possible at this time). can this ticket be closed?

**Comment by parthosa** [comment]
Sure. Thanks for the help
