### ISSUE TITLE
[Question]: Use Env or custom variables in template

### ISSUE THREAD

**Issue by bstopp** [mikepenz/release-changelog-builder-action#1202]
Is the above possible? I don't see anything in the documentation, however i also don't see it in the source anywhere (Not that familiar with TypeScript).

Is this something that would be considered?

**Comment by mikepenz** [comment]
@bstopp thank you for the ticket. 

Can you please explain a bit more on what you aim to achieve? 

I suppose with env and custom variables you both reference to them from the context of GitHub action yaml file?

So practically the default configuration of the action uses a json file -> you can create the json file dyanmically with a bash script or so before the release-changelog-builder is executed, and insert anything dynamic you need. 

The other variant is the configuration of this action by defining the json as part of the yaml. doing so won't allow you to use env variables, but (while I haven't used it personally) I am pretty sure you can use variables from GitHub actions in there. Given as far as I understand GitHub actions replaces all of these prior to a steps execution.

**Comment by bstopp** [comment]
> I suppose with env and custom variables you both reference to them from the context of GitHub action yaml file?

Yes, basically. I'm trying to move away from another Changelog generator to this one, and attempting to keep the output consistent. One of the things displayed is the date of the release. 

Since this isn't available in the GH properties (and even it if was, it wouldn't be formatted correctly). My intent was to have a previous step output the date, then put this in the `env` clause of this action, making it available at runtime for part of the template.

Thoughts?

**Comment by bstopp** [comment]
Right -but my intent was to not have to dynamically change/create the config JSON per run. 

The JSON config file and the Workflow/Action would all be static and part of change control, if i was able to use an `${{env.<var>}}` in the template definition itself.

**Comment by mikepenz** [comment]
In that case the best is most likely to configure via the yaml file of github actions, using the configurationJson config option. Allowing you to pass it right there.

While untested by me, I'm pretty sure you can use github actions env arguments right there
