### ISSUE TITLE
ASSIGNEES not rendering correctly

### ISSUE THREAD

**Issue by Darex1991** [mikepenz/release-changelog-builder-action#1208]
Hi, I just tried using ASSIGNEES for displaying @[user-mention]. 
I tried:
  "pr_template": "- ${{TITLE}} by ${{ASSIGNEES}}",
  "pr_template": "- ${{TITLE}} by ${{ASSIGNEES[*]}}"
  "pr_template": "- ${{TITLE}} by ${{ASSIGNEES[*].author}}" 

but it returns me empty or just text:
<img width="647" alt="Screenshot 2023-08-18 at 13 59 32" src="https://github.com/mikepenz/release-changelog-builder-action/assets/5881611/bb2fc191-7c09-4e71-ba55-0e228351842d">

Is there a different version with this feature? Currently, I'm using `uses: mikepenz/release-changelog-builder-action@v4` or there is a different option to use?

PS. I tried also {{AUTHOR}} and it return my username, but I want to link to the user profile page with nick.

**Comment by mikepenz** [comment]
Good day @Darex1991 . 

Unfortunately there is some difference in how reviewers vs assignees are handled. 

So `REVIEWERS` require `fetchReviewers` enabled, as this uses a different API call. 
`ASSIGNEES` on the other hand should work the way you declared them. 

There's even a test-case where it is verified: https://github.com/mikepenz/release-changelog-builder-action/blob/b0823c5bd8ce94dc285306d884e076927a71ec45/__tests__/releaseNotesBuilderPull.test.ts#L105-L140

By having the placeholder as: `${{ASSIGNEES}}`


Is this on an open source project or closed source? If open source I could test it directly on the commits. 

----

For the `${{AUTHOR}}` if you add the `@` in front, GitHub should automatically link it

**Comment by Darex1991** [comment]
Hi, thanks for help. It is private repo. Using author with @ creates me mentions but not correct (random people) or matched only firstname instead of first+surname.

**Comment by mikepenz** [comment]
Ah apologies. Display name vs username. 🤔

That's something to look into. I suppose author username is what you want.



-------

For the other case I'm not yet sure why the placeholder wouldn't work in your scenario. Even if it didn't have reviewers it should still replace the template with an empty string at least

**Comment by Darex1991** [comment]
There is a option to debug this locally?

**Comment by Darex1991** [comment]
Maybe something wrong with setup:

.github/changelog-configuration.json
```
{
  "template": "## 🚀 What's Changed\n\n\n${{UNCATEGORIZED}}\n",
  "empty_template": "- no changes",
  "pr_template": "- ${{TITLE}} by ${{AUTHOR}}",
  "sort": "ASC",
  "transformers": [
    {
      "pattern": "((?:(?:DEV|Dev|dev))[-]?)\\D(\\w+)",
      "target": "[<a href='Issue-link/DEV-$2'>DEV-$2</a>]"
    }
  ],
  "categories": [],
  "ignore_labels": [],
  "max_tags_to_fetch": 200,
  "max_pull_requests": 200,
  "max_back_track_time_days": 365,
  "exclude_merge_branches": [],
  "tag_resolver": {
    "method": "semver"
  }
}
```

.github/workflows/tag_release.yml
```
- name: Generate Changelog
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-configuration.json
          fromTag: ${{ steps.previoustag.outputs.tag }}
          toTag: v${{ steps.package-version.outputs.current-version }}
          fetchViaCommits: true
          commitMode: true

**Comment by Darex1991** [comment]
Example how works for me 
`"pr_template": "- ${{TITLE}} by @${{AUTHOR}}",`
![Screenshot 2023-08-18 at 18 35 33](https://github.com/mikepenz/release-changelog-builder-action/assets/5881611/5fffe033-9f82-49d8-942a-0f507a1df704)
instead of matching me.

**Comment by mikepenz** [comment]
@Darex1991 yes, you can debug the action locally. You can even place breakpoints if you have the right setup. 

What I usually do is to open the repo with GitHub Codespaces. and then set-up a test case which I execute. 
https://github.com/mikepenz/release-changelog-builder-action#local-testing-

-----

Yes I see. This is actually due to the action getting the name: https://github.com/mikepenz/release-changelog-builder-action/blob/b0823c5bd8ce94dc285306d884e076927a71ec45/pr-collector/src/commits.ts#L95 

however I agree that it will be super helpful to have the `AUTHOR_USERNAME` available too. Will look into expanding this. 

------

For assignees. it will require some debugging I am afraid. As I can't see why it would behave like that for you.

**Comment by mikepenz** [comment]
@Darex1991 one clarification I need. Are you working with pull requests or with commits?

**Comment by Darex1991** [comment]
Mostly there are PRs, but sometimes I have commits. I changed into a commit way because I rebased from one beta branch to develop and changelog displayed that as one PR.

**Comment by mikepenz** [comment]
`AUTHOR` for `commitMode` is now handled the same as for PRs. 

I am not sure I fully understand the last comment. Do you use the `commitMode` to generate the changelog? or PR based? 🤔

**Comment by Darex1991** [comment]
Yeah `commitMode`. Sorry, it is little tricky :D 
Basically. I have "develop" branch and I had "develop_6.2.4" and the meantime releasing I squashed PRs to develop_6.2.4. After releasing develop (and merging to master) I created PR develop_6.24 -> develop and rebased these.
So, when I tried using changelog in PR mode I had only this PR which is true but not expected for me in the future.
After releasing I'm doing normal PRs to develop. This is the reason why in my last message I wrote `Mostly there are PRs, but sometimes I have commits.` :)  Hope I wrote it understandable if not please ask :D

**Comment by mikepenz** [comment]
Ah I see. 

I'd say generally it's better to use this action with PRs as there's just more information available. 
But that's about it. So with the latest release the `${{AUTHOR}}` template will now also be the username for commits, so that should at least fix that part. 

`${{ASSIGNEES}}` will never be filled (as those don't exist for commits) - however should be replaced with an empty string. I tested it, and in the testcases that worked. (as shown in the above screenshot) so I am not sure why that wouldn't work in your case.

**Comment by Darex1991** [comment]
I just checked @{{AUTHOR}} and now it working great :) Thanks for your help and [fast change](https://github.com/mikepenz/release-changelog-builder-action/pull/1210) :)
<img width="593" alt="Screenshot 2023-08-19 at 13 32 14" src="https://github.com/mikepenz/release-changelog-builder-action/assets/5881611/4ecf992c-6bea-421d-9cf8-31fc9d2c2a58">
