### ISSUE TITLE
Filter PR's based on author

### ISSUE THREAD

**Issue by paul-dingemans** [mikepenz/release-changelog-builder-action#1231]
Currently PR are categorized using labels. It would be cool if PR's could alternatively be categorized on author. In this way, a category like "dependencies" could filter on author "renovate".

**Comment by paul-dingemans** [comment]
I found that this is already possible using a `label_extractor`. 
```
    "label_extractor": [
        {
          "pattern": "renovate\\[bot\\]",
          "on_property": "author",
          "method": "replace",
          "target": "dependency"
        }
      ],
```

**Comment by mikepenz** [comment]
@paul-dingemans there is also a different feature which is a bit newer than `label_extractors` you can use. 

Categories can have `rules` provided in addition to organize PRs in categories. An example test: https://github.com/mikepenz/release-changelog-builder-action/blob/af326da47fc20c69fd42234ed91d04ab68c7bbe8/__tests__/transform.test.ts#L553-L576
(this feature is best used with v4 though)

**Comment by paul-dingemans** [comment]
I like syntax above. Unfortunately, it does not seem to work in my use case. After [changing the code](https://github.com/pinterest/ktlint/pull/2211/files) my action flow throws and [error](https://github.com/pinterest/ktlint/actions/runs/5985627530/job/16237903257). None of the PR's seems to be categorized anymore. Am I missing something?

**Comment by mikepenz** [comment]
<img width="658" alt="Screenshot 2023-08-26 at 17 43 31" src="https://github.com/mikepenz/release-changelog-builder-action/assets/1476232/25b58122-4dd9-4e80-969f-fd3ed9797fc8">

It seems there is a problem in the syntax of the config. 

<img width="433" alt="Screenshot 2023-08-26 at 17 44 03" src="https://github.com/mikepenz/release-changelog-builder-action/assets/1476232/9f19a693-0459-4c07-afca-e283bf2886b1">
looks there is a `,` missing.

**Comment by mikepenz** [comment]
One additional advice. Looking at the output for the shell output. you get a bunch of errors as it writes the string as non escaped string. 

<img width="1031" alt="Screenshot 2023-08-26 at 17 45 55" src="https://github.com/mikepenz/release-changelog-builder-action/assets/1476232/dfbc1c75-0541-4552-890b-b4433441dc5b">

The reason for that is how GitHub Actions replaces the template. It basically just puts the string from the variable into that specific location. In non escaped form. 

https://github.com/pinterest/ktlint/blob/master/.github/workflows/generate-changelog.yml#L80

So if you want to output it in bash or use in bash, I highly recommend you setting it into an env variable (this is not specific to this action, but general advice for GitHub actions) 

E.g. something along those lines:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L165-L174

**Comment by paul-dingemans** [comment]
Note that my workflow did work before I change to using `category.rules`.

The label [dependency changelog](https://github.com/pinterest/ktlint/pulls?q=is%3Apr+is%3Aclosed+label%3A%22dependency+changelog%22) is just a single label and should not be separated by a comma.

Is it allowed to have both `labels` and `rules` defined for a single category? According to the documentation it is allowed. In this particular case, I would like to select all PR's for which either the label or the rule is met. After replacing the selection on label with a rule (see https://github.com/pinterest/ktlint/pull/2212) the output is generated correctly.

**Comment by mikepenz** [comment]
I'm currently on the phone so I'll only report on the first. 

I see that it is only a single item, however you miss the comma afterwards, before the next item in the JSON.

**Comment by paul-dingemans** [comment]
Yes, was my mistake. I am so used to the editor highlight and use of trailing comma's that I completely overlooked that.

**Comment by mikepenz** [comment]
@paul-dingemans fully agree
