### ISSUE TITLE
[Question] Ignore PR link Option

### ISSUE THREAD

**Issue by test137E29B** [mikepenz/release-changelog-builder-action#1261]
Is there an option I can use to hide the `- PR: #100` link that's shown in the changelog? I'd like a list of changes without actually linking to every single pull request.

If I've missed this option, please let me know, it's quite a thing to configure

**Comment by mikepenz** [comment]
This comes from the default `pr_template` which defines:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L74

You can change this configuration to which-ever pattern you need for your usecase. 

See more in the `configuration` description of the README:
- https://github.com/mikepenz/release-changelog-builder-action/tree/develop?tab=readme-ov-file#configuration
