### ISSUE TITLE
Possible to use this with GitFlow methodology?

### ISSUE THREAD

**Issue by andrewtheis** [mikepenz/release-changelog-builder-action#1279]
I've been trying to get this action to work with my Mac App repo. My primary CI is Xcode Cloud, and I use some of the [GitFlow methodology](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) for my repository.

Coding process:
- Working branch for created off develop
  -  if first since last release, `MARKETING_VERSION` is manually (for now) bumped in the Xcode project
- PR created for branch & labeled
- PR squashed and merged into develop
- Xcode Cloud generates an RC & pushes to TestFlight

Once all features for a release are completed:
- Release PR created from `develop` >`main`
- Submit latest RC to Apple

On approvcal by Apple:
- Release to store
- Merge (non-squash) Release PR into `main` **<<< Create Release GH Workflow trigger**

So far my Create Release GH Workflow is:
- Clones repo
- Pulls `MARKETING_VERSION` from project file, exports step output
- `mikepenz/release-changelog-builder-action@v4` 
   - **My Issue:** Fails to correctly get commits/PR on `develop` since last marge to `main`
   - I attempted to use `WyriHaximus/github-action-get-previous-tag@v1` to set the `fromTag`, but didn't work out
- `mikepenz/action-gh-release@v0.4.1` with tag_name set to previously exported version found in project file

So, is there a way to configure this action to correctly find all squashed commits/PR on `develop` since the last tag on `main`?

And then furthermore is it possible to tag `main` and not `develop`? Not as big of an issue, but would be nice to have.

Any help is greatly appreciated!

Edit: I know I could change my workflow to just have a `main` branch, and then use `fetchViaCommits: true`, but this would prevent me from doing a hotfix if an issue arrises while I'm in the middle of working on another version...

**Comment by andrewtheis** [comment]
So just after posting this, I was able to get it to work by moving my last release tag from `main` to `develop` which is technically more accurate anyway, since it was the build submitted to Apple. And then set `toTag: develop`. 

Dunno how well this will work if I ever need to do a hot fix, but in case anyone else stumbles upon the same issue, here's my setup:

[create_release.json](https://github.com/mikepenz/release-changelog-builder-action/files/13326473/create_release.json)
[create_github_release.yml.txt](https://github.com/mikepenz/release-changelog-builder-action/files/13326477/create_github_release.yml.txt)

**Comment by mikepenz** [comment]
Thank you very much to provide the solution for others. 👍
