### ISSUE TITLE
can wildcards be used in FromTag ?

### ISSUE THREAD

**Issue by xpillons** [mikepenz/release-changelog-builder-action#1315]
I need to managed two set of tagging versions in my repo, but only considering building the changelog for one set.
first set of tags will be v1.0.x, second set of tags will be w1.0.x, and both tag set would overlap.

In order to build the changelog only for tags v1.0.x can I use a wildcard in the FromTag ?

If not how could I proceed ?
Thank you

**Comment by mikepenz** [comment]
@xpillons it depends on the exact scenario. However there are multiple routes possible. 

The best way for resolving only tags matching the `w` prefix, is to define a `tag_resolver` as part of your config
```
"tag_resolver": {
      "method": "semver",
      "filter": {
        "pattern": "v(.+)",
        "flags": "gu"
      }
    },
```

This one would then make sure only the respective `fromTag` is used. 
Alternative you can also just pass in `from` and `to` directly. 

As I assume both tags exist on the same branch structure, keep in mind that your PRs also will need some identification to be filtered out accordingly. As they are practically part of either tag.

**Comment by xpillons** [comment]
Thanks for the quick answer, I will use your resolver. And yes I will use different tags for identifying the PRs

**Comment by mikepenz** [comment]
Something like:
```
{
  "tag_resolver": {
    "method": "semver",
    "filter": {
      "pattern": "v(.+)",
      "flags": "gu"
    },
    "transformer": {
      "pattern": "v(.+)",
      "target": "$1"
    }
  }
}
```

may do the job for you. (if you only ever care about the `v` releases)

**Comment by mikepenz** [comment]
Please report back if the answer helped, closing in the meantime

**Comment by xpillons** [comment]
yes it help. I applied the filter pattern. Apologize for the late answer.
