### ISSUE TITLE
Author empty in commit mode

### ISSUE THREAD

**Issue by diwic** [mikepenz/release-changelog-builder-action#1327]
The "AUTHOR" shows up empty when using `commitMode: true`. My config is like this:

```
    - name: Create changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commitMode: true
        configurationJson: |
            {
              "categories": [
                {
                  "title": "## Changed since #{{FROM_TAG}}",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}} (#{{AUTHOR}})\n",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000
            }
```

And the resulting changelog:

```
Changed since v1.0.2
fix: Add author to release notes ()
```

Would be nice with support to show the author of the commit. Thanks! :-)

**Comment by mikepenz** [comment]
🤔 it is mapped in the source. it would only be empty if the `commit` did not contain the author: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pr-collector/commits.ts#L119C7-L119C13

**Comment by diwic** [comment]
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/repositories/GithubRepository.ts#L62C1-L63C58

Maybe there is a `commit` that should be `commit.commit` here?

**Comment by mikepenz** [comment]
Can you please try v5.0.0-a03 and validate it works for you that way?

**Comment by diwic** [comment]
Changing from @v4 to @v5.0.0-a03 removes all commit info. It shows just the name of the package and tags with no formatting.

**Comment by mikepenz** [comment]
Apologies. v5 is a major upgrade so it could be some other pieces are not comaptible. I can cherry pick the change on v4, to check it there

**Comment by mikepenz** [comment]
Here's the same commit on the 4.x variant of the action:
https://github.com/mikepenz/release-changelog-builder-action/commit/9784d5c663eed13a5d432f65e1922df2e75ab0f6

Use it via `@9784d5c663eed13a5d432f65e1922df2e75ab0f6`

**Comment by diwic** [comment]
It works better now, thanks for the quick support! 

Although, I also messed around with which email addresses were associated with my account, so there is a chance that the cause for things to be fixed are due to my own changes rather than yours.

**Comment by mikepenz** [comment]
yeah it might be that if the commit identity was not associated with a GitHub identity that it may be empty. It should have contents now either way
