### ISSUE TITLE
Output file lacking hyperlinks to actual PRs

### ISSUE THREAD

**Issue by shozabhussain** [mikepenz/release-changelog-builder-action#1335]
I am trying to save changelog  in a CHANGELOG.md file, however it doesn't have hyperlinks to pull requests

**Comment by mikepenz** [comment]
@shozabhussain the action uses this default template:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L77

You can configure the template to any format you will need for your usecases. Including making out of the auto links which work on gitHub real links for your file

**Comment by shozabhussain** [comment]
@mikepenz Grateful for such quick reply, it's working
