### ISSUE TITLE
How to use output of one step in changelog json file?

### ISSUE THREAD

**Issue by sappusaketh** [mikepenz/release-changelog-builder-action#1336]
I m building docker images before generating change log I want to include those docker images with tags in changelog how can I do it? I m currently using json file with below config
```json
{
  "categories": [
    {
      "title": "## 🚀 New Features",
      "labels": ["feature", "enhancement"]
    },
    {
      "title": "## 🐛 Bug Fixes",
      "labels": ["bug"]
    },
    {
      "title": "## 📦 Dependencies",
      "labels": ["dependencies"]
    },
    {
      "title": "## 📚 Docs",
      "labels": ["documentation"]
    }
  ],
  "max_pull_requests": 1000,
  "max_back_track_time_days": 1000
}
```
can I reference github inputs in json file?
I want to add below markdown

```
## Container images
The following container images are part of this release:
| Images |
| ------------- |
|`image1` |
|`image2` |
```

**Comment by mikepenz** [comment]
Either you build the json manually using shell inserting all you need. Or you configure the configuration as part of your workflow like done here: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L47 which will allow you to use github actions template vars

**Comment by sappusaketh** [comment]
ya currently doing find and replace using shell but wanted to check if thats possible natively thank you
