### ISSUE TITLE
Add all Contributors to Changelog

### ISSUE THREAD

**Issue by Freezor** [mikepenz/release-changelog-builder-action#1337]
Hi maybe this is a new feature request, but I want to add all contributors to a changelog.
I would imagine something like `#{{CONTRIBUTORS}}`

It should then be usable like this:
```json
"template": "# Changelog\n\n#{{CHANGELOG}}\n\n#{{UNCATEGORIZED}}\n\n## Contributors\n\n#{{CONTRIBUTORS}}",
```

Is this planned or possible?

**Comment by mikepenz** [comment]
Please see the open issue: https://github.com/mikepenz/release-changelog-builder-action/issues/940

So far I have not identified: `This depends on the availability of a respective endpoint retrieving contribution information.` 
Happy to take PR proposals or suggestions to properly get this added

**Comment by mikepenz** [comment]
It might be fair to argue that `contributors` of this PR might be simpler compared to `new contributors` in this PR

**Comment by Freezor** [comment]
Fair enough. I will close this, as I see it as a duplicate. I see if I can support you there @mikepenz thanks

**Comment by mikepenz** [comment]
It might be slightly different so feel free to keep it open. I didn't realize initially that you meant to have contributors of this one release. 

For this it should be possible to combine found GitHub user names associated with all collected PRs

**Comment by Freezor** [comment]
I'll test it out. thanks

**Comment by mikepenz** [comment]
It's certainly only partially what you have in mind. as yours would also cover contributors hidden in the commit chain.

**Comment by Freezor** [comment]
Hi. so for now it creates All of the contributors, as I tested your preview @v5.0.0-a04 and the changes of https://github.com/mikepenz/release-changelog-builder-action/pull/1341
If I got time later on, if it is easy to check only unique people.
As you can see in this test (https://github.com/Freezor/aasx-server/releases/tag/v0.3.1.111-aasV3-alpha-latest) it adds my username for each commit/PR.

**Comment by mikepenz** [comment]
Good catch. Will look into improving this one

**Comment by mikepenz** [comment]
updated the `develop` branch to enhance that.
