### ISSUE TITLE
Labels of PRs with capital letters don't match

### ISSUE THREAD

**Issue by MoonLiightz** [mikepenz/release-changelog-builder-action#1345]
I am currently trying to get this action running on a Gitea instance. It surprised me that all PRs are always listed as uncontigorized. By debugging I found out that the capital letters in the standard Gitea label set are the problem. The following part of the code is the reason:

https://github.com/mikepenz/release-changelog-builder-action/blob/bbbdb7a6e6b42a99b1fdfe678ac6c77a7909d149/src/transform.ts#L388

If I remove the mapping to lowercase, everything is categorized as expected. I cannot understand exactly why this mapping is necessary. Is there a solution that the categorization also works with capital letters in the labels?

**Comment by mikepenz** [comment]
Thank you for the report. 

This appears to be a special case with Gitea. GitHub's implementation is always lowercase and as such the action was set-up to match case insensitively. 

I'll need to look to also make the incoming labels from gitea lowercased so that everything is matched case insensitive all the time.

**Comment by MoonLiightz** [comment]
Thank you for the quick answer.

Maybe like this?

https://github.com/mikepenz/release-changelog-builder-action/blob/bbbdb7a6e6b42a99b1fdfe678ac6c77a7909d149/src/repositories/GiteaRepository.ts#L66-L87

```ts
// line 77
labels: pr.labels?.map(label => label.name?.toLowerCase()) as string[],
```

Seems to work well with my test/debug setup.

**Comment by mikepenz** [comment]
Will be in the next major release. Thank you very much!

**Comment by MoonLiightz** [comment]
I have updated the version from `v4` to `v5.0.0-rc01` in my Gitea workflow and can confirm that it now works as expected. Thank you very much for the good work and the fast implementation!
