### ISSUE TITLE
tag resolver filter confusion, mainly include vs exclude

### ISSUE THREAD

**Issue by KonradHoeffner** [mikepenz/release-changelog-builder-action#1349]
Edit: Got it wrong, it is indeed working as an inclusion filter so I revised the issue.

The README description for tag_resolver.filter states "Defines a regex object which is used to filter *out* tags *not* matching." While on careful reading this states that it works as an inclusion, not exclusion, filter, I think this could be written in a clearer way and also helped by an example.
I also tripped over needing to use a double backslash to escape a dot (e.g. to match "24.03") where in the GitHub action tag filter there is only a single one, see the example below.
Because it is hard to debug a GitHub action, it would be nice to have more detailed debug output in the GitHub action logs, for example "applying inclusion filter pattern "xyz*" on 31 tags, 3 tags match the pattern:  ["xyz", "xyzz", "xyzzz"]".
Or "error: your regex is incorrect, please make sure to use regex format xyz and not GitHub action format abc".

```
name: Release
on:
  push:
    tags: '[2-9][0-9]\.[0-9][0-9]'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}}",
              "template": "#{{UNCATEGORIZED}}",
              "tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "[2-9][0-9]\\.[0-9][0-9]"
                }
              }
            }
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.build-changelog.outputs.changelog}}
```

**Comment by mikepenz** [comment]
Thank you for raising this and for improving the documentation on it. 

It's probably worth to also mention in this case that with v5 the tag_resolver can use any other type of regex transformer methods we support. With tags being kept as long as the result of the matcher is not empty.

https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pr-collector/regexUtils.ts#L86-L93

So for example the regexr (works like the regexr online tool) matcher logic can be used which is probably simpler for most:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pr-collector/regexUtils.ts#L59-L64
