### ISSUE TITLE
Add name of users to PRs placeholders

### ISSUE THREAD

**Issue by ilya-hontarau** [mikepenz/release-changelog-builder-action#1360]
Now we have an "Author" placeholder, that's a GitHub username, but I'd like to get another placeholder with the author name(full name).

**Comment by dnaploszek** [comment]
It seems that this could be added in here as another placeholder: 
https://github.com/mikepenz/release-changelog-builder-action/blob/f968a8466a6e8de0586884c110ca34a658ec2ed6/src/repositories/GithubRepository.ts#L62

**Comment by mikepenz** [comment]
Please test it out in v5.0.0-rc03

**Comment by dnaploszek** [comment]
@mikepenz I've tested it, however for some reason it's always empty 😢 - I'm not sure why, as we have our full names in our github profiles - any advice? Sorry for a long time without response

**Comment by mikepenz** [comment]
@dnaploszek you work with PRs for the changelog? or commit based?

**Comment by dnaploszek** [comment]
Squashed and merged commits from tag to tag

**Comment by mikepenz** [comment]
Then this is the problem I believe. commits don't have GitHub users associated if I am not mistaken. It should work for PRs though

**Comment by dnaploszek** [comment]
That's odd, afaik we were using something different earlier that could extract the user name and it was working there, however I just jumped into this to resolve it at a later date so I cannot provide more details out of the box - maybe Ilya could - I'll sync with him on this soon

**Comment by dnaploszek** [comment]
Well I've investigated it myself + talked with the team, for some reason it's not filled - sorry to bother, unfortunately this didn't solve our issue, we'll need to use github logins for references

**Comment by mikepenz** [comment]
Thanks for following up. I wonder if there's something else we can do. if you had a reproducible public open source repo or something we can test with faster that would help
