### ISSUE TITLE
Accept header and GitHub Enterprise instances

### ISSUE THREAD

**Issue by mrivnak1** [mikepenz/release-changelog-builder-action#1366]
Hi all,

We've been looking to integrate this action with some of our workflows but ran into an issue where the api of our GitHub Enterprise instance responds with `application/json` whereas the octokit package only accepts `application/vnd.github+json` by default and results in a 406. Is there a way that this action could accept either, or have some way to configure this externally?

**Comment by mikepenz** [comment]
Good day @mrivnak1 

The action uses the `octokit` library to do the requests, so I am afraid there's not a lot we can change in that perspective. https://github.com/octokit/rest.js


With the baseurl being used to configure the `octokit` instance: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/repositories/GithubRepository.ts#L193-L205

**Comment by mrivnak1** [comment]
I see, I think there's something going wrong with SAML auth that ends up returning completely the wrong result. I've tried to run the request directly with the headers that I expect octokit to provide and that works. Closing this unless I can get a better idea what's going on. SAML auth has been an issue with other external actions/services so not entirely surprised there.
