### ISSUE TITLE
Doing an echo to file may break content

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#137]
**Info:** not the action itself executed the command, but a step afterwards (echo to file)
```yaml
    - name: Make release notes
      run: echo "${{steps.build_changelog.outputs.changelog}}" > .github/release-notes.md
```

Hi

So something strange happened when we released https://github.com/vshn/k8up/releases/tag/v1.0.0-rc2:

![image](https://user-images.githubusercontent.com/12159026/103363511-8a073500-4abb-11eb-9144-4d52ba337ee6.png)

In https://github.com/vshn/k8up/pull/200, the title was 
```
Disable LEADER_ELECTION by default for `make run run_kind`
```
which actually cause the action to execute `make run run_kind`:
```
$ cat Makefile
run: fmt vet
	go run ./main.go
```
That looks almost like a security issue to me? :)

at the very least it screws the changelog. Meanwhile I have edited the Title, but it's still unexpected

**Comment by mikepenz** [comment]
@ccremer thank you very much. I just looked into this and it seems not the action did execute the code, but the echoing into the file

![image](https://user-images.githubusercontent.com/1476232/103365681-ea4ca580-4ac0-11eb-88e4-a339170cb5c0.png)

Which brings us now back to: https://github.com/mikepenz/release-changelog-builder-action/issues?q=is%3Aissue+is%3Aclosed

I think that's a good enough reason now to do this

**Comment by ccremer** [comment]
Oh, interesting! Didn't think of that...
I can't spontaneously think of a command that would prevent execution. https://github.com/mikepenz/release-changelog-builder-action/issues/136 would probably the safest approach. I might not be the first to get the idea to use echo for this problem :)

**Comment by mikepenz** [comment]
even if only passively related: https://github.com/mikepenz/release-changelog-builder-action/pull/138

**Comment by mikepenz** [comment]
v1.3.0 adds a new flag to define a file to write the output to

**Comment by ccremer** [comment]
This is awesome, thank you very much! 🎉

**Comment by wdoug** [comment]
Following up on this for the case where you actually do just want to echo the output (for [testing for example](https://github.com/wdoug/git-flow-github-actions/blob/dev/.github/workflows/test-changelog.yml)):

> The best practice to avoid code and command injection vulnerabilities in GitHub workflows is to set the untrusted input value of the expression to an intermediate environment variable

-- https://securitylab.github.com/research/github-actions-untrusted-input

So you could do something like this:
```yml
- name: print changelog
  env:
    CHANGELOG: ${{steps.build_changelog.outputs.changelog}}
  run: echo "$CHANGELOG"
```
