### ISSUE TITLE
please add CalVer (Calendar Versioning) support

### ISSUE THREAD

**Issue by KonradHoeffner** [mikepenz/release-changelog-builder-action#1383]
In addition to the default tag-resolver `"method": "semver"`, it would be very helpful to also have "calver" like this:

```
    "tag_resolver": {
      "method": "calver",
    }
```

I have many repositories with Calendar Versioning and building a functioning configuration for that is cumbersome and error prone.
Right now I am using the following:

```
  "tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "[2-9][0-9]\\.[0-9][0-9]"
                }
              }
```

The above has worked for a while but now it rejects correct tags, like "23.08" and "24.04", and on the contrary it picks up incorrect tags, like "23.10.21".
To reduce all this effort, a standardized "calver" would be really appreciated.

**Comment by mikepenz** [comment]
`calver` is practically supported by the `sort` version. as `YYYY.MM.DD` will always correctly sort. 
The same applies for `YY.MM`.

**Comment by mikepenz** [comment]
Closing as not planned. `calver`does sort properly using the sort based ordering logic in the action. 

```
   tag_resolver: {
        method: 'sort'
    },
```
