### ISSUE TITLE
Tags not filtered correctly

### ISSUE THREAD

**Issue by dimofeev** [mikepenz/release-changelog-builder-action#1401]
Hi Mike,

I have a question related with tag_resolver. I have different tags created (prod-x, v1.1.1, stg-x) and I would like to build the changelog by comparing only prod tags (for example changes between prod-100 and prod-101). All other tags must be ignored.

I'm using `@v5.0.0` version with the following configuration:

```json
"tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "prod-(.+)",
                  "flags": "gu"
}
```

However using this configuration does not compare correct tags - it compare stg-100 and stg-101. Am I wrong with my configuration or there is an issue ?

Thank you in advance for your help.

**Comment by mikepenz** [comment]
which `method` for  the filter do you use? 
See a pretty similar test case here: https://github.com/mikepenz/release-changelog-builder-action/blob/6816fa41158c91d38ad60fabcce677bc48c3d3f4/__tests__/tags.test.ts#L110

**Comment by dimofeev** [comment]
The `method` is `sort`. I'll try right now with `match`. Thanks, Mike.

**Comment by mikepenz** [comment]
Careful. method for the filter. not method for the tag_resolver. 
(see the nesting)

**Comment by dimofeev** [comment]
Thanks, Mike! It is working as expected now when using the `sort` method.
