### ISSUE TITLE
[Question] Prerelease support with all PRs merged in main branch

### ISSUE THREAD

**Issue by dimofeev** [mikepenz/release-changelog-builder-action#1404]
Hi Mike,

Just a quick question for the prerelease support. With the current configuration support can I create prerelease that list all the PRs merged between the latest prod tag and main branch? Here is my use case:

1. I have tag `prod-10` created for example and respective release for it added.
2. I have several PRs merged into main after the `prod-10` tag was created. After each PR merge I want to run GitHub action that generate pre-release and list respective PRs as part of it.
3. Once I create `prod-11` tag delete the pre-release and create release for this tag.

Well, I believe this is a bit tricky use case so I was wondering if this is supported. Thank you in advance for your reply.

**Comment by mikepenz** [comment]
Hi @dimofeev 

If I follow properly you basically want `ignorePreReleases` always set to `true` in that case the action will look for the latest full release to collect the changelog

**Comment by dimofeev** [comment]
Thank you, Mike. I'll give a try.
