### ISSUE TITLE
Problem getting latest tags

### ISSUE THREAD

**Issue by dimofeev** [mikepenz/release-changelog-builder-action#1406]
Hi Mike,

Seems there is a problem getting the latest tags in some cases. Here is how my configuration look like:

              "tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "prod-(.+)",
                  "method": "match",
                  "flags": "gu"
                }
              }

Now, when this got executed the following output is printed:

📘 Reading input values
  ℹ️ Retrieved configuration via 'configurationJson'.
  ℹ️ Running in PR mode.
🔖 Resolve tags
  ℹ️ Found 200 (fetching max: 200) tags from the GitHub API for service1
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  sha:xxxxxxx
  /usr/bin/git describe --abbrev=0 --tags sha:xxxxxxx
  prod-120
  🔖 Resolved current tag (prod-120) from 'git rev-list --tags --skip=0 --max-count=1'
  ℹ️ Only one tag found for the given repository. Usually this is the case for the initial release.
  /usr/bin/git rev-list --max-parents=0 HEAD
  sha:xxxxxxx
  🔖 Resolved initial commit (sha:xxxxxxx) from 'git rev-list --max-parents=0 HEAD'
  🔖 Resolved previous tag (sha:xxxxxxx) from the tags git API
🚀 Load data
  🚀 Load pull requests
  ℹ️ Comparing service - 'sha:xxxxxxx...prod-120'
  ℹ️ Found 0 commits from the GitHub API for service1
  Warning: ⚠️ No commits found between - sha:xxxxxxx...prod-120

I have a lot of prod tags and the prod-120 is not the first one (prod-119 exists for example). The interesting part here is that for some other repos it is correctly comparing the previous and last tags. Do you have an idea what might be the problem? Thank you in advance for your help.

**Comment by dimofeev** [comment]
Seems that the cases when this is working fine is when we have less than 200 tags...

**Comment by mikepenz** [comment]
@dimofeev thanks for the report. 

I looked up GitHub's docs again, and it does not have sorting for fetching tags: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-tags--parameters

Given also this comment here: https://stackoverflow.com/a/19615235 it's a tough one. 

You can adjust the count of tags the action fetches: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L62

Or you can provide the previous tag manually.

**Comment by dimofeev** [comment]
Thanks, Mike. I tried with `max_tags_to_fetch: 200` but again, it is not working...

So it seems that the only way is to use `fromTag` and `toTag`. I created bash script to get the latest prod tags (for example prod-110 and prod-109) and then I pass them as follow:

              fromTag: "${{ env.previous_prod_tag }}"
              toTag: "${{ env.latest_prod_tag }}"

However it fallback to semver again when executed: 

  🔖 Resolved current tag (v1.0.105) from the tags git API
  🔖 Resolved previous tag (v1.0.104) from the tags git API

I saw in the documentation the following statement: "fromTag is resolved by sorting tags using [semver](https://semver.org/). Tags not following semver are filtered out. Check the [configuration](https://github.com/mikepenz/release-changelog-builder-action?tab=readme-ov-file#configuration-specification) for alternatives."

However I'm not quite sure which exactly configuration I'm missing right now...

**Comment by dimofeev** [comment]
This is my whole configuration:

          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}} (##{{NUMBER}})",
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": [
                    "feat",
                    "feature",
                    "Feature"
                  ]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": [
                    "fix",
                    "bug",
                    "Fix"
                  ]
                },
                {
                  "title": "## 🛠️ Chores",
                  "labels": [
                    "chore",
                    "Chore"
                  ]
                },
                {
                  "title": "## 🧪 Testing",
                  "labels": [
                    "test",
                    "qa",
                    "automation",
                    "unit",
                    "integration"
                  ]
                },
                {
                  "title": "## 📦 Dependencies",
                  "labels": [
                    "deps",
                    "Auto update"
                  ]
                },
                {
                  "title": "## ✨ Other",
                  "labels": []
                }
              ],
              fromTag: "${{ env.previous_prod_tag }}"
              toTag: "${{ env.latest_prod_tag }}"
              "label_extractor": [
                {
                  "method": "regexr",
                  "pattern": "^(chore|feat|fix|bug|test|unit|integration|Auto update)",
                  "target": "$1",
                  "on_property": "title"
                }
              ]
            }

**Comment by mikepenz** [comment]
Didn't you mean you had more than 200 tags? As such I meant you wanna probably configure a number higher than that. 

Can you show additional log? Because if `from` and `to` tags are provided the action will just use those and not try to find them itself. could it be that it might not have passed properly? 

Also the passed configuration appears to mix arguments to the action with configuration options. 

`fromTag` and `toTag` are arguments to the action
<img width="723" alt="Screenshot 2024-12-13 at 10 28 19" src="https://github.com/user-attachments/assets/21da4ee1-c151-4882-ba50-ad23a0eb13a2" />

While `label_extractor` and the others are part of the `configurationJson`

**Comment by dimofeev** [comment]
Yes, I put the arguments on the wrong place. So here is the corrected configuration:

        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}} (##{{NUMBER}})",
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": [
                    "feat",
                    "feature",
                    "Feature"
                  ]
                }
               ....
              ],
              "label_extractor": [
                {
                  "method": "regexr",
                  "pattern": "^(chore|feat|fix|bug|test|unit|integration|Auto update)",
                  "target": "$1",
                  "on_property": "title"
                }
              ]
            }
          fromTag: "${{ env.previous_prod_tag }}"
          toTag: "${{ env.latest_prod_tag }}"

But again it takes the semvers tags even previous_prod_tag and latest_prod_tag are resolved correctly...

Here is the log from the execution:

Run mikepenz/release-changelog-builder-action@v5.0.0
📘 Reading input values
  ℹ️ Retrieved configuration via 'configurationJson'.
  ℹ️ Running in PR mode.
🔖 Resolve tags
  ℹ️ Found 1540 (fetching max: 200) tags from the GitHub API for service
  🔖 Resolved current tag (v1.0.105) from the tags git API
  🔖 Resolved previous tag (v1.0.104) from the tags git API
🚀 Load data
  🚀 Load pull requests
  ℹ️ Comparing service - 'v1.0.104...v1.0.105'
  ℹ️ Found 2 commits from the GitHub API for service
  ℹ️ Fetching PRs between dates 2024-12-09T07:28:44.000Z to 2024-12-09T07:29:20.000Z for service
  ℹ️ Retrieved 2 release commits for service
  ℹ️ Retrieved 1540 PRs for service in date range from API
  ℹ️ Retrieved 1 merged PRs for service
�� Build changelog
  ℹ️ Sorted all pull requests ascending: {"order":"ASC","on_property":"mergedAt"}
  ℹ️ Using 0 transformers to rewrite content
  ℹ️ Ordered all pull requests into 6 categories
  ✒️ Wrote 45 categorized pull requests down
  ✒️ Wrote 0 non categorized pull requests down
  ✒️ Wrote 0 open pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template

**Comment by mikepenz** [comment]
Can you confirm please if `toTag` and `fromTag` are correctly passed in as configs:

E.g. showing what inputs the action get: 
<img width="545" alt="Screenshot 2024-12-13 at 12 31 31" src="https://github.com/user-attachments/assets/c2d7107f-5a67-4daa-bf9c-ad8ede10e516" />

I double checked, the action will directly use the from and to which is configured on action level. which makes me wonder if `env.previous_prod_tag` and the other env var are both empty

**Comment by dimofeev** [comment]
Yep, just found that I skipped this part during my tests (i.e. the redirect to GITHUB_ENV) and forgot to add it after that. Sorry for the troubles. Everything is working just fine right now.

Thank you for the awesome help!

**Comment by mikepenz** [comment]
Thank you very much. Glad we could find a solution!
