### ISSUE TITLE
Idea: Use commit messages, instead of only merge-commits / PRs to build changelog

### ISSUE THREAD

**Issue by ndom91** [mikepenz/release-changelog-builder-action#141]
Hi Mike,

I've been looking for something almosstttt exactly like this for a while, but I want to use the normal commit messages between tags to create the release changelog. Not only merge commit / PRs.

That doesn't seem possible at the moment. Is it?

Thanks for the cool gh action!

**Comment by mikepenz** [comment]
Hi @ndom91 based on my research I didn't focus on that aspect as most other actions seem to do that, but not based on PRs. 

What do the other actions lack that you would love to use? 
E.g. I am trying to find / see an argument to add the functionality to this action.

Thank you so much!

**Comment by ndom91** [comment]
Ah maybe I've missed other actions, I would just like to do basically the same thing this action already does, except for for projects where you're mainly working by yourself and just making commits to main. 

Those where you're not working with branches/PRs all the time, but would still like a coherent changelog. Know what I mean?

**Comment by mikepenz** [comment]
There are a few problems with this approach. More specifically speaking about the differences between commits and PRs

a commit won't for example have:
- lables
- milestone
- asignee
- reviewer
- the merge commit hash
- a number

so a big amount of information is missing. most of it could probably be filled with placeholders by staying empty, but the core part of `labels` which is required to organise things and sort will also be missing. so you will loose a big amount of benefits which you only get with PRs

----

That being said, I may look into providing a base mode, but you'd sadly miss out on all the real goodies.

**Comment by ndom91** [comment]
Ah good point, a commit does not have a lot of that stuff that makes for the interesting changelog info in the end anyway. 

Oh well, thanks for taking the time to talk this through :+1:

**Comment by mikepenz** [comment]
@ndom91 but as a tiny surprise. I added "experimental" support to the action for it. You can enable it via the `actionMode` flag: https://github.com/mikepenz/release-changelog-builder-action/pull/151/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R26

Play around with it and let me know what you think

**Comment by ndom91** [comment]
Oh wow, thanks a ton! I'll give this a shot soon. Appreciate it!

**Comment by mikepenz** [comment]
@ndom91 the latest release now also has a new feature allowing to use a regex to extract "labels" from commit messages. Which makes this release now able to categorize changelogs based on commit messages if you have their category in some extractable form defined

**Comment by eniltonj** [comment]
It worked fine for me ! 
Nice work !

I am using this conf:
```json
{
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": ["feature", "features"]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": ["fix", "fixes"]
    },
    {
      "title": "## 🧪 Other",
      "labels": ["other"]
    }
  ],
  "sort": "ASC",
  "template": "${{CHANGELOG}}",
  "pr_template": "- ${{TITLE}}\n",
  "empty_template": "- no changes",
  "label_extractor": [
    {
      "pattern": "\\[(.*)\\].*",
      "target": "$1"
    }
  ],
  "transformers": [
    {
      "pattern": "\\[.*\\] (.*)",
      "target": "$1"
    }
  ],
  "max_tags_to_fetch": 200,
  "max_pull_requests": 200,
  "max_back_track_time_days": 365
}
```
An option to sort using the commit messages (the target in transformer) could be great.
