### ISSUE TITLE
How do I make it generate the same thing GitHub would auto-generate for between the two tags?

### ISSUE THREAD

**Issue by melyux** [mikepenz/release-changelog-builder-action#1414]
While I appreciate the custom format, I would like to use the same one GitHub uses. How do I make this action generate that default format?

**Comment by mikepenz** [comment]
The GitHub format looks like:

```
## What's Changed
* Update `dist-check` CI job by @mikepenz in https://github.com/mikepenz/release-changelog-builder-action/pull/1185


**Full Changelog**: https://github.com/mikepenz/release-changelog-builder-action/compare/v4.0.0-rc06...v5.1.0-rc02
```

It basically only has 1 category which is `What's Changed`
and then it uses: PR Title `by` PR Author `in` PR URL

and finishes with a fixed link to the diff. 


You can find all placeholders and configuration options for this action in the README here: https://github.com/mikepenz/release-changelog-builder-action?tab=readme-ov-file#template-placeholders

-----

That said if all you want is the GitHub changelog, you can just use an action which uses GitHub's APi to generate the release notes like: https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing

<img width="958" alt="Screenshot 2024-12-26 at 10 42 52" src="https://github.com/user-attachments/assets/0ee5003f-aa0d-4c6b-bc54-212d5007513e" />


https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
