### ISSUE TITLE
Identify breaking changes

### ISSUE THREAD

**Issue by marksie1988** [mikepenz/release-changelog-builder-action#163]
Hey, It would be good if this would identify any breaking changes. 

for example, I can add a "breaking" label (or based on semver changes) that would be in addition to say adding a "feature" which then would flag this feature as a breaking change. 

currently there is no way to identify a breaking change that i can see without manually editing the release.

**Comment by mikepenz** [comment]
@marksie1988 would an additional "breaking changes" section work for example? 

You could for example tag breaking changes as such, and have that as the first section. 


Alternative you could for example have it as part of the title and use the transformer to have this specially added to the entry:

```
    "transformers": [
      {
        "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
        "target": "- $4\n  - $6"
      }
    ],
```

-----

Maybe you could also add some example changelog with the "breaking" label as you'd love it to show up?

**Comment by marksie1988** [comment]
I have had a think and I feel that adding a new breaking changes section would actually work best.

Would this add two entries if it had say the breaking and feature labels? Or would it only out it under the first section.

**Comment by mikepenz** [comment]
It will show up in both sections. So this should cover the additional section case. 
Hope this helps

**Comment by marksie1988** [comment]
Yes that is great thank you 👍
