### ISSUE TITLE
Use global .GitHub folder if local one doesn't exist

### ISSUE THREAD

**Issue by marksie1988** [mikepenz/release-changelog-builder-action#167]
I have loads of repositories however the config I use is the same for them all. 

I use another action that will check the global .GitHub folder for the configuration file if it doesn't exist in the local repo .GitHub file. 

Would it be possible to do this?

**Comment by marksie1988** [comment]
Example: https://github.com/robvanderleek/create-issue-branch

**Comment by mikepenz** [comment]
@marksie1988 the action uses the config provided in reference to the root of the repository. 

So you can place the config in the root of the repo too if you prefer, for example the builds in the repo itself are not located in the `/.github` folder, but instead in `/configs`: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L62

**Comment by marksie1988** [comment]
Yes the issue with this is that i need the config file in every repository. 

Where as if the default location was inside the .github folder, if the file wasnt in the local repo, the .github files from the org could be used.

**Comment by mikepenz** [comment]
But github actions are executed per repo. I am not sure I follow. 

In case you have an action in a repo which checks out multiple repositories you can still configure whatever location is required.

i don't think the action should have to provide a fallback path logic, beside the capability so you can configure the location of the config. 

if you want to have that follow some logic you could have step before this action which would look for the path, write it into an actions variable which is then provided as config path.

**Comment by mikepenz** [comment]
Please let me know if this resolved your question :). closing for the time being
