### ISSUE TITLE
Update docs with additional information on using checkout

### ISSUE THREAD

**Issue by hartman-michael-PFG** [mikepenz/release-changelog-builder-action#170]
If using this action in a workflow triggered by push on something other than refs/tags, e.g.
```
on:
  push:
    branches:
      - 'main'
```

it is necessary to specify a `fetch-depth` of 0 in order for tag information to be included in the repo. Otherwise this action's git command will fail when attempting to describe the repo's tags.

```
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # indicates all history for all branches and tags. needed for changelog.
```

**Comment by mikepenz** [comment]
@hartman-michael-PFG thanks for your report. 

There are actually 2 solutions to this. 

Either the fetch-depth is adjusted to a value to have the relevant tags in range (0 would mean all history which in a ton of cases would significantly slow down the checkout) 

this can be made obsolete too if the `toTag` is provided. 

I'll add the info to the README. thanks!
