### ISSUE TITLE
Configuration being ignored somehow?

### ISSUE THREAD

**Issue by cmsj** [mikepenz/release-changelog-builder-action#207]
Hey!

I've been trying to make use of this action, initially to show a preview of how release notes will look, as a comment in each PR.

My workflow yml is: https://github.com/Hammerspoon/hammerspoon/blob/master/.github/workflows/pr_release_note_preview.yml
and the configuration file is: https://github.com/Hammerspoon/hammerspoon/blob/master/.github/workflows/release_notes_config.json

I'm pretty sure they are correct, and I have a checkout action, but the comments that get put on PRs just say "* no changes", see: https://github.com/Hammerspoon/hammerspoon/pull/2691#issuecomment-789693712

I think that indicates that my configuration json isn't being applied properly, because I specified a different `empty_template`

If it helps, this should show the Actions run that produced that comment, with debug logging enabled: https://github.com/Hammerspoon/hammerspoon/runs/2022165003?check_suite_focus=true

What am I doing wrong? :)

**Comment by cmsj** [comment]
Sorry, I was being dumb and had an error in the JSON after I'd last validated it. Thanks!

**Comment by mikepenz** [comment]
@cmsj anything we can improve in the messaging for that case? 

Currently the warning is logged like this:

```
⚠️ Configuration provided, but it couldn't be parsed. Fallback to Defaults.
```

**Comment by cmsj** [comment]
Yeah that message is fine, it was my fault for not expanding the Reading Input Values section of the log, to see it :)
