### ISSUE TITLE
Can we categorize pull requests by title?

### ISSUE THREAD

**Issue by wdoug** [mikepenz/release-changelog-builder-action#208]
I would like to be able to categorize pull requests based on pattern matching of their titles. 

For example, if a pull request begins with `fix:` then treat it as a bugfix. Essentially [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), but at a pull request level. I see the `label_extractor`, but if I am reading the Readme correctly it appears that only applies on pull request bodies, not titles, is that correct?

Thanks for this great action by the way!

**Comment by mikepenz** [comment]
@wdoug thank you so much!

That's a great idea, was not yet thinking of that. And yes you are correct, right now the `label_extractor` would only be done currently on the `body` (e.g. commit message, pull request body) 

https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L23-L33

I think it makes absolute sense to include this feature.

**Comment by mikepenz** [comment]
May be able to already have a look at this today

**Comment by mikepenz** [comment]
Do you by coincidence have a repo where you use `conventional commits`? I'd love to add a testcase for this, but PR titles of my projects don't work for that purpose

**Comment by wdoug** [comment]
Hmm. I thought that I had an open-source project that used conventional commits, but when I just went and looked the ones I thought I had been using it on didn't seem to be following that convention (at least anymore...).

**Comment by mikepenz** [comment]
oh well :D no test for now (yet) then. in either way, you can configure this now too. Really believe it was a nice feature to add

thanks

**Comment by wdoug** [comment]
@mikepenz, I just tried testing this feature on a [branch](https://github.com/wdoug/git-flow-github-actions/tree/try-label-extractor) of my little dummy repo I've been testing with [here](https://github.com/wdoug/git-flow-github-actions). The [echoed changelog from my manual test action](https://github.com/wdoug/git-flow-github-actions/runs/2043626045?check_suite_focus=true) isn't giving me the results I would have thought it should if I understood the docs correctly.

Here's my test [configuration](https://github.com/wdoug/git-flow-github-actions/blob/try-label-extractor/.github/workflows/release-changelog-config.json), and [here](https://github.com/wdoug/git-flow-github-actions/blob/d1be5ada48baed22c10ea80bb4ddeeb115e9ec4f/.github/workflows/test-changelog.yml#L24-L32) is my action setup (I tried switching it to the `develop` branch if that is what it does, to get this new feature).

I would have thought with that setup it would have categorized [this pull request](https://github.com/wdoug/git-flow-github-actions/pull/55) (`Fix changelog action`) as a fix. Is that right, or was I misunderstanding the configuration?

**Comment by wdoug** [comment]
Oh, I see the new feature is on the `main` branch and included in version `v1.6.0`...
