### ISSUE TITLE
Label extraction doesn't make sense

### ISSUE THREAD

**Issue by invakid404** [mikepenz/release-changelog-builder-action#333]
Hello, I've been using this action for a while now and I'm loving it, but there's a thing I just can't wrap my head around.
Label extraction is very counter-intuitive. I'd expect that label extraction matches the given value against the pattern and uses the *target* as a label, but apparently, it replaces the pattern with the target and uses that as a label.
Is this intended behavior, and if yes, how is this expected to work with multiline values? My use case is that I want to look for specific headers in the PR body and use its name as a label. For example, I want to match `## Feature:` and extract "feature" to use as a label. Is this possible with the current implementation?
Also, doesn't it make sense to match labels in a case-insensitive way? GitHub doesn't consider label names to be case-sensitive, so shouldn't this be reflected in this action?

**Comment by mikepenz** [comment]
@invakid404 I really like the proposal to match labels in a case insensitive way. 

In regards to the other question. Yes it should be able to identify `Feature` from the given `## Feature`. Ultimately the idea was that if a label is written inside the description / commit message, that it can be extracted from there.

**Comment by invakid404** [comment]
I've opened a PR with a reimplementation of label extraction the way I imagine it should work. Let me know what you think about it @mikepenz.

**Comment by mikepenz** [comment]
Can you maybe provide a specific example of what there may be impossible?

With the label extractor you can find any type of group in the source string. 
And bring it afterwards in the format you need it as label. 

For example if you have a description or title which contains the string `TEST X Y Z` you could write a regex to match `X` `Y` `Z` in their own group each, and then construct a label which would be `$3$2$1 TEST` resulting in label `ZYX TEST` for example

**Comment by invakid404** [comment]
> Can you maybe provide a specific example of what there may be impossible?
> 
> With the label extractor you can find any type of group in the source string.
> And bring it afterwards in the format you need it as label.
> 
> For example if you have a description or title which contains the string `TEST X Y Z` you could write a regex to match `X` `Y` `Z` in their own group each, and then construct a label which would be `$3$2$1 TEST` resulting in label `ZYX TEST` for example

Anything multiline is impossible with the current implementation. That's why I think it should at least match line by line, and that's exactly what I've done in the PR.

If you want an actual example, here is one:
```
## Feature:

[x] Implemented something
[x] Closes <some issue>
```

Our PR template is something close to that. What I want to be able to do with the label extractor is match just the `## Feature:` and extract just `feature` from it. The current implementation will do the replace, but will leave the rest of the lines untouched, and that doesn't work for us.

**Comment by invakid404** [comment]
I hope you can see where I'm coming from. In retrospect, I probably should've worded the issue I'm having better in the first place, but I only got to think about it properly when I got to implementing it.

I'm not committed to the particular implementation in the PR, it was more to describe how I'd expect label extraction works. The high-level view of my proposal is that extraction happens separately for every line of the body. If you have a better idea which would work for my use case, feel free to decline the PR/request changes.

**Comment by mikepenz** [comment]
Maybe an alternative solution would be to adjust the `Regex` in javascript to add the `dotall` or `multiline` config :/ 

https://stackoverflow.com/a/1068308/325479

**Comment by invakid404** [comment]
Dotall would work, it'd just mean all my regexes need to be wrapped in ".*"

**Comment by invakid404** [comment]
I suppose you can also just provide a way to specify flags for the regex pattern in the config, that way you'd be able to do pretty much anything.

**Comment by invakid404** [comment]
In this case, I've updated the PR, as I agree it's a better and more generic solution to just allow any flags to be specified for the regex.

**Comment by invakid404** [comment]
@mikepenz I just tested the new changes with our repos and they work! This is what I ended up doing:

```
  "label_extractor": [
    {
      "pattern": ".*##\\s+(\\w+).*",
      "target": "$1",
      "flags": "gis"
    }
  ]
```

**Comment by invakid404** [comment]
Can we tag the new changes so we can start using them ASAP and close this issue?

**Comment by mikepenz** [comment]
@invakid404 I'll do so soon. for now you can use the git hash instead of a version number to use it :)

**Comment by invakid404** [comment]
Alright, I'll close this then. Thanks!

**Comment by mikepenz** [comment]
Thank you once again for the PR :) and enhancement

**Comment by mikepenz** [comment]
@invakid404 thank you once again. Went ahead and released it as v2. Great work!
