### ISSUE TITLE
body: - no changes ?

### ISSUE THREAD

**Issue by vvatelot** [mikepenz/release-changelog-builder-action#413]
Hello @mikepenz I maybe have a misconfiguration and I am trying to figure out how to make your github action work. So, sorry if this issue is not completely relevant...

I used the example you provide in the readme and I make PR on my project: 

When I add a tag, the [action works fine](https://github.com/cnumr/ecoindex_python/runs/3191784189?check_suite_focus=true), but it results with a `no changes` body... Did I miss something ?
![image](https://user-images.githubusercontent.com/12939091/127501544-f07fbedc-5c6c-4346-8ced-f9e6b97e5769.png)

**Comment by mikepenz** [comment]
Hey @vvatelot 

The action by default uses the merged PRs to generate the changelog for. 
Those PRs are categorized via their label. 

According to your log it had 2 PRs it kept, but those were not categorized so it would not inlclude them in the default template. 

<img width="881" alt="Screenshot 2021-07-29 at 16 09 36" src="https://user-images.githubusercontent.com/1476232/127506956-2a84db11-6307-4ddc-9120-5d785de67d8c.png">

You can include uncategorized PRs in your changelog too if you like

**Comment by vvatelot** [comment]
Alright!
I read your documentation and things are clear now:
- I use tags on my PR (using https://github.com/cnumr/ecoindex_python/blob/master/.github/workflows/pr-labeler.yml to auto label my PR based on branch name)
- I added a configuration file https://github.com/cnumr/ecoindex_python/blob/master/.github/config/changelog.json
- I added a checkout step in the CI before the changelog action
And... Voilà!
![image](https://user-images.githubusercontent.com/12939091/127623597-8f8218a8-a335-4dc1-bd58-9041ef6c1010.png)

Thanks again @mikepenz for this great tool and your help :+1:

**Comment by mikepenz** [comment]
@vvatelot glad I was able to help. 

Please let me know if there's something we can improve in the docs, to help others. 

Thank you very much

**Comment by vvatelot** [comment]
The things that confused me is that I used the [full sample](https://github.com/mikepenz/release-changelog-builder-action#full-sample-%EF%B8%8F) and assumed that everything would work out of the box. But I needed to use tags and then add a config file to make the mapping of the tags / categories.
So maybe just explain this? :thinking:

**Comment by mikepenz** [comment]
Good point, will add a note to the full sample that the PRs are required to be labelled with one of the default labels to show up, otherwise custom configuration will be needed. 

Thank you very much.
