### ISSUE TITLE
Environment variable 'INPUT_BODY' exceeds the maximum supported length

### ISSUE THREAD

**Issue by BublilDaniel** [mikepenz/release-changelog-builder-action#423]
hi just started using github in my team
i get this error
![image](https://user-images.githubusercontent.com/57449012/128217031-6be3d7ab-c16a-4b8d-bfd7-f56aa8ca20a2.png)
this results the entire history of my repo..

i use fetch-depth : "0"
if not it will throw error saying no tag found

if I am trying to specify toTag
i get this
![image](https://user-images.githubusercontent.com/57449012/128217318-99226612-5767-480e-bc97-04e0f1bf89dc.png)

i just want those changelog to work from the most recent tag to the current pushed tag

i am using commitMode

Thanks Guys!

**Comment by mikepenz** [comment]
@BublilDaniel That's an interesting case. 

It seems the resulting changelog for your project would be huge. 

Commit mode can result in significant output in case a ton of commits have been made between 2 tags. 

Do you have additional log output from the action highlighting what exactly it did. e.g. how many commits, if it identified the right from-to tags/hashes?

**Comment by BublilDaniel** [comment]
Yes you are correct, the repo didn't had any tag at all.
So I made some and tested again, now it works great!

Thanks
Ps I think you should limit the changelog length to the maximum.

**Comment by mikepenz** [comment]
Thank you very much
