### ISSUE TITLE
Using current head as `toTag`

### ISSUE THREAD

**Issue by marier-nico** [mikepenz/release-changelog-builder-action#442]
Hello!

I'm currently running into an issue with my usage of this action. The way I'd like to use it is to generate the changelog by using all pull requests merged between the last tag, and the current head of the currently checked out branch. From the documentation, it seemed like the action really required having two tags. Is there a way to make it use the current head? Or is this a new feature that could potentially be added?

Currently I have a work-around that requires adding a step to create a new tag with the current head just before building the changelog. It's not too bad, but it's definitely inconvenient.

If that's of any help, here is the workflow I'm talking about : https://github.com/marier-nico/pr-bump/blob/main/.github/workflows/release.yml

Many thanks! :smile:

**Comment by mikepenz** [comment]
@marier-nico the action also allows to specify the `toTag` or `fromTag` configuration as `ref`. 

You can see that the tests include this case: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/__tests__/releaseNotes.test.ts#L59

-----

So doing something like this here: https://stackoverflow.com/a/61699863 (get the SHA for the head, set it as output variable, and use to configure the action step)

**Comment by marier-nico** [comment]
Nice, that works perfectly! Sorry if it was an obvious question, I just couldn't really find the answer in the docs :slightly_smiling_face:
