### ISSUE TITLE
It's not detecting my labels.

### ISSUE THREAD

**Issue by charlou-aredidon** [mikepenz/release-changelog-builder-action#483]
I created and attached the `release_notes` label on some of my pull requests (merged) but it's going to **non-categorized** list (logs)

## my config:
```json
{
  "categories": [
    {
      "title": "## 🚀 Release Notes",
      "labels": [
        "release_notes"
      ]
    }
  ],
  "ignore_labels": [],
  "sort": "ASC",
  "template": "${{CHANGELOG}}",
  "pr_template": "- ${{TITLE}} (#${{NUMBER}})",
  "empty_template": "- no changes",
  "label_extractor": [],
  "duplicate_filter": {
    "pattern": "\\[ABC-....\\]",
    "on_property": "title",
    "method": "match"
  },
  "transformers": [],
  "max_tags_to_fetch": 200,
  "max_pull_requests": 200,
  "max_back_track_time_days": 365,
  "exclude_merge_branches": [],
  "tag_resolver": {
    "method": "sort"
  },
  "base_branches": []
}
```

## Sample pull requests
![image](https://user-images.githubusercontent.com/90191659/133207241-f356261f-abc5-4d35-9268-9519ed56d444.png)

## Logs
```bash
📘 Reading input values
🔖 Resolve tags
🚀 Load pull requests
  ℹ️ Comparing myusername/ci_cd_flutter_poc - 'v1.2.0...v1.2.1'
  ℹ️ Found 8 commits from the GitHub API for myusername/ci_cd_flutter_poc
  ℹ️ Fetching PRs between dates 2021-09-13T12:05:04.000Z to 2021-09-13T12:22:18.000Z for myusername/ci_cd_flutter_poc
  ℹ️ Retrieved 68 merged PRs for myusername/ci_cd_flutter_poc
  ℹ️ Retrieved 8 release commits for myusername/ci_cd_flutter_poc
  
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: ASC
  ℹ️ Used 0 transformers to adjust message
  ✒️ Wrote messages for 5 pull requests
  ℹ️ Ordered all pull requests into 3 categories
  ✒️ Wrote 0 categorized pull requests down
  ✒️ Wrote 5 non categorized pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```

**Comment by charlou-aredidon** [comment]
I also wonder why there are 5 pull requests in non-categorized. I only have 3 pull requests with my specific label.

**Comment by mikepenz** [comment]
@charlou-aredidon is this project private or an open source project? 

Based on the log message `Ordered all pull requests into 3 categories` it sounds like the configuration may not have been loaded. 
Could you please check if the configuration was available?
<img width="400" alt="Screenshot 2021-09-14 at 08 55 12" src="https://user-images.githubusercontent.com/1476232/133209844-34201533-efe0-4a23-8c9f-d91b529228a7.png">

**Comment by charlou-aredidon** [comment]
Good idea. I did not noticed that. Will check in a few minutes..
The project is private. But some of the steps contains hardcoded tokens so I can't make it public right away..

**Comment by mikepenz** [comment]
@charlou-aredidon will look into improving the logging around the configuration loading, should make it show up in the `Reading input values` section. 

In regards to 5 pull requests, could there have been more merges within those 2 tags?

**Comment by charlou-aredidon** [comment]
Currently there are only 3 PRs with the `release_note` label.

**Comment by mikepenz** [comment]
That's alright, when the configuration will be picked. those 2 without the label will be uncategorized, and the 3 with the label should show up in their respective category.

**Comment by charlou-aredidon** [comment]
Is my configuration correct though?
What I wanted to do is automatically get PRs with `release_note` label to be added into our changelogs.

**Comment by mikepenz** [comment]
The configuration looks correct (scanned quickly through it) 

The main problem seems to be that the configuration was not used by the action. 

Can you please provide how the action is specified within your workflow configuration? 
E.g. how do you provide the configuration file to the action?
> https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L106

**Comment by charlou-aredidon** [comment]
```yaml
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.4.0
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It's in the root path.

**Comment by charlou-aredidon** [comment]
My repo currently has:
- 1 open PR
- 73 closed
  - 71 merged (2 closed but not merge)
    - 3 labeled with `release_note` (merged)
- The open PR does not have any labels.

## Here's an updated logs
```bash
📘 Reading input values
🔖 Resolve tags
🚀 Load pull requests
  ℹ️ Comparing myusername/ci_cd_flutter_poc - 'v1.2.0...v1.2.1'
  ℹ️ Found 8 commits from the GitHub API for myusername/ci_cd_flutter_poc
  ℹ️ Fetching PRs between dates 2021-09-13T12:05:04.000Z to 2021-09-13T12:22:18.000Z for myusername/ci_cd_flutter_poc
  ℹ️ Retrieved 71 merged PRs for myusername/ci_cd_flutter_poc
  ℹ️ Retrieved 8 release commits for myusername/ci_cd_flutter_poc
  
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: ASC
  ℹ️ Used 0 transformers to adjust message
  ✒️ Wrote messages for 5 pull requests
  ℹ️ Ordered all pull requests into 1 categories
  ✒️ Wrote 0 categorized pull requests down
  ✒️ Wrote 5 non categorized pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```

**Comment by charlou-aredidon** [comment]
Seems the config is loading properly now. 

`Ordered all pull requests into 1 categories`

**Comment by charlou-aredidon** [comment]
But my label is not detected still.

**Comment by mikepenz** [comment]
You referred in your comments a few times `release_note`. Is the label `release_notes` or `release_note`?

**Comment by charlou-aredidon** [comment]
Sorry for the confusion. I updated all my configuration and my label to `release_note` and everything is now pushed to all my branches. To make sure of this. I am going to make a `test_label`. And get back to you again.

I will update some of my merged PRs and add the `test_label`.

**Comment by mikepenz** [comment]
You can also execute this action locally if you have node set up on your environment. 
Can assist to setup a test case to run it locally, so you can test it significantly faster than doing it within github actions.

**Comment by charlou-aredidon** [comment]
You might also want to check your source code for mapping the labels. It seems you're using `toLocaleLowerCase()` which might cause problems in some machines and languages. I'm running macOS-11 in my action files and I don't know which language it's running though.

How about changing this to `toLowerCase()` and also add a detailed logs.
- The section `Reading input values` is showing nothing. It's better to show something there like dumping the entire `configuration.json` to ensure that correct configuration is being used.

https://github.com/mikepenz/release-changelog-builder-action/blob/2deff3d4f5d63a1fa8412b47c5104fb4797947cc/src/pullRequests.ts#L132

**Comment by charlou-aredidon** [comment]
Not sure how hard or easy it is to test this locally. But you can comment it here I think. Other people might also see this issue.

**Comment by charlou-aredidon** [comment]
I checked with the GitHub API. My repo PRs is definitely having the correct label.

![image](https://user-images.githubusercontent.com/90191659/133244597-a8b82ee8-2eec-4134-8f6a-716d5a6caccf.png)

```json
  "categories": [
    {
      "title": "## 🚀 Release Notes",
      "labels": [
        "test_label"
      ]
    }
  ],
```

**Comment by mikepenz** [comment]
@charlou-aredidon looks this problem may be due to the `duplicate_filter`, currently investigating locally. 

For reference, instructions on running tests locally:
- download the repository 
- run `npm install` // install npm dependencies
- run `npm run build && npm run package` // build the project

After this tests can be executed via:
- `npm test`

To execute a specific test class execute `npm test -- issue.test.ts`

See an example for `issue.test.ts` blow:

```javascript
import {buildChangelog} from '../src/transform'
import {PullRequestInfo} from '../src/pullRequests'
import moment from 'moment'
import { DefaultConfiguration, Configuration } from '../src/configuration';

jest.setTimeout(180000)

// test set of PRs with lables predefined
const pullRequestsWithLabels: PullRequestInfo[] = []
pullRequestsWithLabels.push(
  {
    number: 1,
    title: '[XYZ-1234] - this is a PR 1 title message',
    htmlURL: '',
    baseBranch: '',
    mergedAt: moment(),
    mergeCommitSha: 'sha1',
    author: 'Mike',
    repoName: 'test-repo',
    labels: new Set<string>().add('test_label'),
    milestone: '',
    body: 'no magic body for this matter',
    assignees: [],
    requestedReviewers: []
  },
  {
    number: 2,
    title: '[XYZ-4321] - this is a PR 2 title message',
    htmlURL: '',
    baseBranch: '',
    mergedAt: moment(),
    mergeCommitSha: 'sha1',
    author: 'Mike',
    repoName: 'test-repo',
    labels: new Set<string>().add('issue').add('fix'),
    milestone: '',
    body: 'no magic body for this matter',
    assignees: [],
    requestedReviewers: []
  }
)

it('Match multiple labels exhaustive for category', async () => {
  const customConfig = Object.assign({}, DefaultConfiguration)
  customConfig.categories = [
    {
      "title": "## 🚀 Release Notes",
      "labels": [
        "test_label"
      ]
    }
  ]
  customConfig.ignore_labels= [],
  customConfig.sort= "ASC",
  customConfig.template= "${{CHANGELOG}}",
  customConfig.pr_template= "- ${{TITLE}} (#${{NUMBER}})",
  customConfig.empty_template= "- no changes",
  customConfig.label_extractor= [],
  customConfig.duplicate_filter= {
    "pattern": "\\[ABC-....\\]",
    "on_property": "title",
    "method": "match"
  },
  customConfig.transformers= [],
  customConfig.max_tags_to_fetch= 200,
  customConfig.max_pull_requests= 200,
  customConfig.max_back_track_time_days= 365,
  customConfig.exclude_merge_branches= [],
  customConfig.tag_resolver= {
    "method": "sort"
  },
  customConfig.base_branches= []

  const resultChangelog = buildChangelog(pullRequestsWithLabels, {
    owner: 'mikepenz',
    repo: 'test-repo',
    fromTag: '1.0.0',
    toTag: '2.0.0',
    failOnError: false,
    commitMode: false,
    configuration: customConfig
  })

  expect(resultChangelog).toStrictEqual(
    `expected changelog`
  )
})
```

**Comment by charlou-aredidon** [comment]
Looks interesting. I'll try this.

**Comment by mikepenz** [comment]
@charlou-aredidon I think I know now what the issue is. 

The `deduplication` filter requires the successful resolution to the `identifier` as it would be extracted by the rule. 
In case no `identifier` can be extracted, as in your case, the PR itself will be dropped from the list of changes. 

Looking to adjust this behaviour in the next version, so that deduplication will not drop PRs which did not result in an identifier. 

For the time until there's an action update, I'd recommend to remove the deduplication filter unless you require it?

**Comment by mikepenz** [comment]
Tagging v2.4.1 right now, which will include more logs, around the faced issues + fix the behaviour on de-duplication
