### ISSUE TITLE
[bug]: Failed build from no names found

### ISSUE THREAD

**Issue by T145** [mikepenz/release-changelog-builder-action#557]
```
Run mikepenz/release-changelog-builder-action@v2
/usr/bin/docker exec  7c5faac10627816750acbe1904cdd48fa7fab1204d4e09f3548c8335864b2001 sh -c "cat /etc/*release | grep ^ID"

📘 Reading input values
🔖 Resolve tags
  ℹ️ Found 8 (fetching max: 200) tags from the GitHub API for T145/black-mirror
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 128
```
https://github.com/T145/black-mirror/runs/4003988476?check_suite_focus=true#step:6:20

I'm simply using the action like so:
```yml
- name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Before releasing and am unsure why it's failing.

**Comment by smith-it** [comment]
I'm having the same problem - hoping @mikepenz can shed some light on what I'm doing wrong.

Here's the relevant workflow:
```
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v2.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        toTag: ${{ github.sha }}
```

Here's the relevant build log:
```
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.sha
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'sha'
##[debug]=> '81107d3ba3e665f1360df205569b0a4736b755f4'
##[debug]Result: '81107d3ba3e665f1360df205569b0a4736b755f4'
##[debug]Evaluating condition for step: 'Build Changelog'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build Changelog
##[debug]Loading inputs
##[debug]Loading env
Run mikepenz/release-changelog-builder-action@v2.6.0

::set-output name=failed::false
##[debug]steps.github_release.outputs.failed='false'
::group::📘 Reading input values
📘 Reading input values
  ##[debug]GITHUB_WORKSPACE = '/home/runner/work/*redacted repo*/*redacted repo*'
  ##[debug]repositoryPath = '/home/runner/work/*redacted repo*/*redacted repo*'
  ℹ️ Configuration not provided. Using Defaults.
  
  ::set-output name=owner::*redacted org*
  ##[debug]steps.github_release.outputs.owner='*redacted org*'
  ##[debug]Resolved 'owner' as *redacted org*
  
  ::set-output name=repo::*redacted repo*
  ##[debug]steps.github_release.outputs.repo='*redacted repo*'
  ##[debug]Resolved 'repo' as *redacted repo*
  ::endgroup::
::group::🔖 Resolve tags
🔖 Resolve tags
  (node:1907) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  ℹ️ Found 1 (fetching max: 200) tags from the GitHub API for *redacted org*/*redacted repo*
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 128
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Build Changelog
```

There is one tag on the repo of `1.0.0`.

Any suggestions?

**Comment by T145** [comment]
My guess would the second reason Mike provided.

**Comment by mikepenz** [comment]
@smith-it based on the log it looks like there is only a single tag during the execution of the action. 

In such a case (if the GitHub API only has a single tag) and no other `from` point is provided, the action will try to retrieve an initial commit using the `git cli`, which in this case looks to have not found anything. which would indicate that either the repo was shallow cloned (e.g. without any tags) or was not available at all.

**Comment by smith-it** [comment]
Hmm... interesting. So, I assumed the `fromTag` would automatically resolve itself to `1.0.0` as it's the only tag in the repo and exists on an older commit hash than that triggering the build.

I am checking out the code in this job but was using the default fetch depth. This is the updated checkout step:
```
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

This fixed the `fatal: No names found, cannot describe anything.` error, however, I'm surprised to see the change log generated was `no changes`. There's a ton of commits, all with messages that exist between the tagged version and the current commit hash.

Is this an artifact of the first run or is there something else I'm missing in the `release-changelog-builder-action` configuration?

**Comment by mikepenz** [comment]
@smith-it that's actually an interesting case. 

In your situation you don't want to go from tag to something before, but from latest commit to previous tag. I'd need to check if that's currently something automatically handled if you provide the `git hash` as `toTag` or if it will not resolve back to the other tag either. 

Generally the action allows you to provide `from` and `to`tag as either git tag name or the git has for those particular states, and the action will look to reference these. and only use the PRs in-between as releases. 

----

For the second part of your comment. If you look into the log it notes: `Wrote 254 non categorized pull requests down` Which indicates that while it found those PRs, the did not have `labels` attached which are used to categorize. 

The default categories it would use are:

```json
"categories": [
      {
        "title": "## 🚀 Features",
        "labels": ["feature"]
      },
      {
        "title": "## 🐛 Fixes",
        "labels": ["fix"]
      },
      {
        "title": "## 🧪 Tests",
        "labels": ["test"]
      }
    ]
```

and the default template is only the CATEGORIZED PRs:

https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L52



And yes please, I think it will be better to open a new issue to track this
