### ISSUE TITLE
Add option to edit existing release

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#565]
### Problem

Let's consider a GitHub workflow where the GH release is created by another action, but doesn't provide a good release changelog. It would be cool if this changelog action can edit a release changelog of a release that already exists.

The main reason I'm asking this is because some actions do not allow to customize the release changelog. And even if such option is requested as a feature, the maintainers might be inactive or reject such a config option.
Example: https://github.com/helm/chart-releaser-action

### Proposal

Add a config flag that replaces the body of an existing GH release if it finds one. I'm open to the name, but could be something like `replaceExistingRelease` or `editExistingReleaseBody`

This action would then be placed after another action created the release.

**Comment by mikepenz** [comment]
@ccremer thank you for the report. At this time the `release-changelog-builder-action` itself does not create the release nor does it actually modify the release. 

It's sole purpose is generate the changelog, which you can then use in any form needed. 
- update the release on github
- send an e-mail
- update a file in the repo with the changelog
- take the text for any follow up action in the action

So for projects I use this in, I forward the changelog to the `softprops/action-gh-release` action, which will handle updates / creation of the GitHub related release. 

https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L105-L119

**Comment by ccremer** [comment]
Yeah, after writing this issue I just realized this too :)
An alternative would be something like https://github.com/tubone24/update_release

Gonna close this as there are already ways to solve the problem.

**Comment by mikepenz** [comment]
I chose actually specifically not to include GitHub release modification in this action, as I believe that is partial out of scope. And would rather offer full flexibility to the person/dev-team integrating it. 

It also gives the advantage of not needing write permissions within the action, so read is practically enough.
