### ISSUE TITLE
Consider tag prefixes or pattern to build changelog

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#566]
### Problem

Consider cases where a mono-repository creates tags for multiple, different release "scopes".
For example, there could be tags like `api-v1.0.2` and `client-v2.2.3`. If there's another release for `api`, the changelog for the `api-` prefixes should only contain the changes from the last `api-` release tag and not contain changes targeting the `client`

Real world examples: 
* https://github.com/appuio/charts/releases
* https://github.com/kubernetes-sigs/kustomize/releases

### Proposal 1

Add a config option to set a specific regex pattern to match tags.
Example: `tagPattern: 'api-'`
Tags:
```
- api-v1.0.1
- api-v1.1.0
- client-v1.0.2
```
Pushed tag: `api-v1.1.0`
The changelog action would ignore `client-v1.0.2` since it doesn't match `api-` regex and use `api-v1.0.1` instead.
This config option might be incompatible with other options, depending on implementation (you can answer that best I guess).

The pattern could also be computed from the pushed tag (e.g. drop the vx.x.x substring)
note: the `v` prefix might be optional as well for semver parsing.

### Proposal 2

Add config option that only respects the same prefix (following a certain pattern).
Example: `matchingTagPrefix: true`
Tags:
```
- api-v1.0.1
- api-v1.1.0
- client-v1.0.2
```
Pushed tag: `api-v1.1.0`

The changelog action would detect that `api-` is a prefix to the actual version number. It then knows that `client-v1.0.2` should be ignored (even though `v1.0.2` is "more recent" than `v1.0.1`).
To make use of this option, release tags should follow a certain naming standard that needs to be documented, e.g. `<prefix>-<semver>-<prerelease-suffix>`

This proposal has the advantage over proposal 1 where one doesn't need to specify the pattern, it uses more of a "convention" instead. However, it may be less flexible and requires users to follow an opinionated naming scheme

Maybe both proposals could make sense. One could choose which one to use, but these may be exclusive depending on implementation. Though personally I'd favor proposal 1.

**Comment by ccremer** [comment]
Note: This feature would be especially powerfull with #565 when creating Helm releases

**Comment by ccremer** [comment]
Wow, already implemented?! You're fast, thanks a lot :)
I'll try to test it out today.

**Comment by mikepenz** [comment]
For now it's a simple regex filter to filter out tags not relevant. 

You can see it here in the testcase: https://github.com/mikepenz/release-changelog-builder-action/commit/ed954db1f67d8c6800eaee966fd43dba85097fac#diff-4a285a1d715ea63386ed421d94d3e443232d0f73a4375b2862f5a39dae899901R95-R126

You are welcome :)

**Comment by ccremer** [comment]
I've got a quick question: Can I define the pattern via workflow input or env var or the like? Or is this only available in `configuration.json`?
If it's only available via json file, I would need to do some `jq` magic to define the pattern after a checkout.
The use case would be that depending which sort of Tag gets pushed (e.g. `api-`) the pattern should by dynamically configured to match `api` tags. But if `client-` tags get pushed, then the pattern should target `client-` tags.

I don't mind doing a `jq` patch, since I most likely need to parse a prefix and build the pattern in the workflow anyway as a separate step. I just wanted to ask/confirm if that's the intended behaviour.

**Comment by mikepenz** [comment]
@ccremer yes it would be specified via the `configuration.json`. correct. 

Potentially it could be considered to have the json be passed as string to the action directly at some point, but that wouldn't change things in this case now I guess.

**Comment by ccremer** [comment]
Perfect, thanks :+1:
