### ISSUE TITLE
tag_resolver.filter doesn't recognize previous tags

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#571]
### Summary

I'm testing out the new feature introduced in #569 .
It looks like given a pattern, it doesn't match any previous semver tags and instead falls back to the initial commit

### Context

Given tags in this [repository](https://github.com/ccremer/charts/releases):
* fronius-stack-0.1.2
* fronius-stack-0.2.0
* a bunch of others

Workflow: https://github.com/ccremer/charts/blob/d50315a9dbc83331adc260802b7f689bc879f25c/.github/workflows/changelog.yml

### Actual behavior

From https://github.com/ccremer/charts/runs/4121893890?check_suite_focus=true

<details>
<summary>Configuration</summary>

  ```json
   {
    "pr_template": "- ${{TITLE}} (#${{NUMBER}})",
    "categories": [
      {
        "title": "## 🚀 Features",
        "labels": [
          "enhancement",
          "feature"
        ]
      },
      {
        "title": "## 🛠️ Minor Changes",
        "labels": [
          "change"
        ]
      },
      {
        "title": "## 🔎 Breaking Changes",
        "labels": [
          "breaking"
        ]
      },
      {
        "title": "## 🐛 Fixes",
        "labels": [
          "bug",
          "fix"
        ]
      },
      {
        "title": "## 📄 Documentation",
        "labels": [
          "documentation"
        ]
      },
      {
        "title": "## 🔗 Dependency Updates",
        "labels": [
          "dependency"
        ]
      }
    ],
    "template": "${{CATEGORIZED_COUNT}} changes since ${{FROM_TAG}}\n\n${{CHANGELOG}}",
    "label_extractor": [
      {
        "pattern": "^(?!\\[fronius-stack\\])",
        "method": "replace",
        "target": "ignore",
        "on_property": "title"
      }
    ],
    "tag_resolver": {
      "filter": {
        "pattern": "fronius-stack-(.+)"
      }
    }
  }
  ```
</details>

<details>
<summary>Logs</summary>

```console

📘 Reading input values
  ℹ️ Configuration successfully loaded.
  
  
🔖 Resolve tags
  (node:1576) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  ℹ️ Found 55 (fetching max: 200) tags from the GitHub API for ccremer/charts
  🔖 Resolved current tag (fronius-stack-0.2.0) from the 'github.context.ref'
  ℹ️ Only one tag found for the given repository. Usually this is the case for the initial release.
  /usr/bin/git rev-list --max-parents=0 HEAD
  89032f1d7504ee71d95e937f0f275fdb5cde4ed2
  🔖 Resolved initial commit (89032f1d7504ee71d95e937f0f275fdb5cde4ed2) from 'git rev-list --max-parents=0 HEAD'
  🔖 Resolved previous tag (89032f1d7504ee71d95e937f0f275fdb5cde4ed2) from the tags git API
  
🚀 Load pull requests
  ℹ️ Comparing ccremer/charts - '89032f1d7504ee71d95e937f0f275fdb5cde4ed2...fronius-stack-0.2.0'
  ℹ️ Found 220 commits from the GitHub API for ccremer/charts
  ⚠️ Adjusted 'fromDate' to go max 365 back
  ℹ️ Fetching PRs between dates 2020-11-05T21:04:07.000Z to 2021-11-05T21:04:07.000Z for ccremer/charts
  ℹ️ Retrieved 63 merged PRs for ccremer/charts
  ℹ️ Retrieved 220 release commits for ccremer/charts
  
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: ASC
  ℹ️ Used 0 transformers to adjust message
  ✒️ Wrote messages for 63 pull requests
  ℹ️ Ordered all pull requests into 6 categories
  ✒️ Wrote 6 categorized pull requests down
  ✒️ Wrote 57 non categorized pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```
</details>

<details>
<summary>Generated release changelog</summary>

```md
6 changes since 89032f1d7504ee71d95e937f0f275fdb5cde4ed2
  
  ## 📄 Documentation
  
  - [fronius-stack] Bogus change to test changelog generator (#93)
  
  ## 🔗 Dependency Updates
  
  - Update helm/chart-releaser-action action to v1.2.1 (#63)
  - Update docker.io/emby/embyserver Docker tag to v4.6.0.50 (#62)
  - Update module github.com/gruntwork-io/terratest to v0.34.7 (#64)
  - Update module github.com/gruntwork-io/terratest to v0.35.1 (#71)
  - Update docker.io/library/telegraf Docker tag to v1.19 (#84)
```
</details>

### Expected behaviour

The changelog should only be containing PR `#93` and diff from tag `fronius-stack-0.1.2`, e.g.
```md
1 changes since fronius-stack-0.1.2
  
  ## 📄 Documentation
  
  - [fronius-stack] Bogus change to test changelog generator (#93)
```

**Comment by mikepenz** [comment]
@ccremer thank you very much for the very in depth description of the problem. 

There are 2 problems. 

Running it locally shows in the logs directly that the tags are not in semver format, so we'll also need to provide an option to transform the tag prior to sorting, so any custom tag format will be handled.

Beyond that, it would also be very helpful to commit all changes, as while I was adding the test case for the filter itself, I missed calling that method. 

Very sorry for this overlook :/

**Comment by mikepenz** [comment]
Created a fix + new feature to handle this usecase. 

Could you please give it a try before I do a new release? https://github.com/mikepenz/release-changelog-builder-action/pull/572

Additionally a temporary test case for your usecase:
https://github.com/mikepenz/release-changelog-builder-action/tree/feature/571_test

**Comment by ccremer** [comment]
Sorry for the late response, I wasn't offline the weekend.

So the fix and the new transformer config seems to work fine: It now correctly identified the intended previous tag:
```md
2 changes since fronius-stack-0.1.2

## 📄 Documentation

- [fronius-stack] Bogus change to test changelog generator (#93)
- [fronius-exporter] Bogus change to test changelog generator that should be ignored (#94)
```
(https://github.com/ccremer/charts/commit/a1cabe95e53232e7486edb14db8bc906828c4e0d)

Thanks for test cases specific for my repo, I wouldn't have known how to configure the transformer :)

There is one last piece missing to getting it all working.
As you can already see above, I did another bogus PR with label "Documentation". However, since it has a different title, I expected it to be ignored using the following config snippet:
```json
    "label_extractor": [
      {
        "pattern": "^(?!\\[fronius-stack\\])",
        "method": "replace",
        "target": "ignore",
        "on_property": "title"
      }
    ],
```
The goal is to ignore irrelevant PRs without permanently adding ignore-labels.
I somehow expected it to "add" the `ignore` label in memory to each PR that doesn't have the `[fronius-stack]` in the title, so that those PRs get ignored.

In hindsight, probably the more robust approach would be adding a label to each PR (e.g. `chart/fronius-stack`) and only consider PRs that have them, and then categorize by type of change (in this case `documentation`). Is this already possible with the `exhaustive` option? If yes, then I could do some `jq` magic to make that label filtering dynamic.

I'm not sure how to get this working. Should I create a new issue for this problem?

**Comment by mikepenz** [comment]
@ccremer no worries. It was weekend :). thank yo for having a try. 

Not sure, possibly (if you don't mind) I'd include this case to the standard test cases, so we cover this new filtering behaviour with tests. 

----

I see, I believe it should be possible to make this work with the exhaustive option. 

The fastest would be to run the action locally (via the tests). So you can quickly try out different things without the need to re-run actions over and over. 
It also allows you to debut theoretically. 

Let me know if you'd need some help to run a specific test class or so?

**Comment by ccremer** [comment]
> Not sure, possibly (if you don't mind) I'd include this case to the standard test cases, so we cover this new filtering behaviour with tests.

Fine by me

> I see, I believe it should be possible to make this work with the exhaustive option.
> 
> And yes I believe this should go into it's own ticket.

Opened new issue #576 

> The fastest would be to run the action locally (via the tests)

I'll try to get a setup working locally, will report back.
