### ISSUE TITLE
Dynamically ignore PRs

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#576]
Follow up of #571 

### Problem

With the `tag_resolver.filter` and `tag_resolver.transformer` feature we can now filter and ignore tags when building a PR "diff" between 2 tags.
For example, it's possible to search for the "previous" version of a tag matching a prefix (e.g. `api-v1.0.1` and `api-v1.1.0` while ignoring `client-v1.0.2` between). The action would then consider PRs between those `api-` tags and not treat `client-v1.0.2` as the previous version of `api-v1.1.0`.

What's currently not easily doable is to ignore PRs that shouldn't make it into a changelog based on the tag value.
While one can configure `ignore_labels`, this is static and applies to all "release scopes". 
The goal is to dynamically ignore PRs one certain conditions.

In the given example, a PR labelled `documentation` but meant for the `api` should only be included in the changelog if the release tag also contains `api-`. For any `client` releases, that PR should not be included.

### Workaround

It should be possible to use the `exhaustive` option in the category labels. To make it dynamic, one would need to patch the config to all categories before building a changelog (e.g. with `jq`).
However, there's a limitation: If a category "bugfixes" is built with either `bug` or `fix`, when there's `api` label and `exhaustive=true`, then a PR would need both `bug` AND `fix` (before it was OR). Alternatively, only `bug`/`api` pairs or `fix`/`api` are allowed

### Proposal 1

Add a config option `filter_labels`.
Only PRs having one label from this list is further categorized based on other, additional labels. Alternatively, all labels are required. Maybe configurable with a `method` param?

This allows to categorize PRs based on labels like `documentation` or `bug` without requiring a scoped label, e.g. `api/documentation` and `api/bug`. One can just label `documentation` and based on the tag, the action would automatically figure out if a `documentation` PR is appropriate or not.

There is a limitation: Requiring a dedicated label for each "release scope" (e.g. `api` and `client`) works well for small list of release scopes. For highly dynamic release scopes it becomes more and more a pain to maintain those labels on GitHub. That's where Proposal 2 might be an alternative.

### Proposal 2

Extract a label from label extractor and then filter on those.
Consider the following config snippet:
```json
  "ignore_labels": [
    "ignore"
  ],
  "label_extractor": [
    {
      "pattern": "^(?!\\[api\\])",
      "method": "replace",
      "target": "ignore",
      "on_property": "title"
    }
  ],
```
Any PR that _doesn't_ have the `[api]` prefix at the beginning of the PR title internally gets the `ignore` applied, so that the action will ignore unrelated PRs. This label extractor feature already exists today, but somehow it doesn't really work. 
I need to confirm/debug this first to exclude a config error. It's possible that this proposal is obsolete if that approach already works but I did an error on my end.

This method would be more flexible and dynamic due to not requiring an existing set of labels compared to Proposal 1, but it makes it more fragile (depending how good the pattern is).

**Comment by ccremer** [comment]
So far I can confirm that the workaround with `exhaustive` works.

**Comment by ccremer** [comment]
Regarding proposal 2.

So, the config snippet provided does work like the following:
```
ℹ️ Added label ignoregenerate a changelog after helm-chart-releaser published release
ℹ️ Added label [fronius-stack] bogus change to test changelog generator
ℹ️ Added label ignore[fronius-exporter] bogus change to test changelog generator that should be ignored
```
patched transform.ts:
```ts
        for (const label of extracted) {
          core.info('ℹ️ Added label ' + label)
          pr.labels.add(label)
        }
```
I misunderstood the `target` property (based on its name) to be the label that will be applied if the pattern matches. However, it's the string that gets applied where `pattern` matches.
I'll try adapting my pattern, maybe I can do some regex so that the whole title gets replaced with `ignore`

**Comment by ccremer** [comment]
So, with a pattern like `        "pattern": "^(?!\\[fronius-stack\\])(.*)",` I get the following additional labels on a PR:
```
ℹ️ Added label ignore
ℹ️ Added label [fronius-stack] bogus change to test changelog generator
ℹ️ Added label ignore
```
This now works as intended. Internally, the PR will get another label that is exactly like the title, not sure about the implications of this. One could label a PR `bug` and then name it `documentation` and it would come up in 2 different categories... It would be a rare edge case though and I don't think an action is required here. Maybe you know a better pattern/target?

I would still prefer proposal 1 for a more robust approach, especially for a finite set of "release scopes"/labels.

**Comment by mikepenz** [comment]
Glad you could resolve it. Did you get the project set-up locally now and used a test to quicker iterate?


I'll have a look, I think the pattern should be possible to be easier. which would in that case make solution 2 the cleaner solution I believe.

**Comment by ccremer** [comment]
> Did you get the project set-up locally now and used a test to quicker iterate?

I cloned the `feature/572_test` branch and edited the config and src files until I got a working `npm test` result. Didn't figure out how I could debug in VScode or run only a selective test (not a TS/js dev)

**Comment by mikepenz** [comment]
If you are in the `terminal` view of VSCode, there's the plus button on the right side, chose `JavaScript Debug Terminal`
<img width="392" alt="Screenshot 2021-11-08 at 18 45 50" src="https://user-images.githubusercontent.com/1476232/140791958-efdded93-8531-489c-995c-7970c84bc259.png">

And then within that terminal, just start the test in a single file like:

```
npm test -- fronius.test.ts   
```

**Comment by ccremer** [comment]
[it's...beautiful](https://github.com/ccremer/charts/releases)

Thanks for the VSCode hints

I got it working, but I've had to choose the workaround with the `exhaustive` option. Some PRs are [bot-generated](https://github.com/ccremer/charts/pull/96) and thus I can't rely on label extractor to attach labels from titles.
