### ISSUE TITLE
A bunch of unexpected behaviour

### ISSUE THREAD

**Issue by darrellwarde** [mikepenz/release-changelog-builder-action#605]
Sorry for the not very specific title, but having a few issues! 

Firstly, the `exhaustive` setting does not appear to be working as expected. Despite having this enabled for each category (features, fixes, tests) on a category label plus a product label, features are appearing in the fixes list, etc.

Secondly, date ranges between tags don't seem to be resolving properly. Despite finding the right tag range (`@neo4j/graphql@2.4.0...@neo4j/graphql@2.5.0`), the date range that it infers from that (`2021-11-01T10:03:42.000Z to 2021-12-01T13:39:00.000Z`), as the previous tag was made 22 days ago, so just over a week over what it's some up with as the start date.

Any ideas on the above? Thanks for any help!

Full log below:

```
Run mikepenz/release-changelog-builder-action@v1
  with:
    configuration: config/release-changelog-builder-action/configuration-graphql.json
    toTag: @neo4j/graphql@2.5.0
    ignorePreReleases: false
    failOnError: false
    commitMode: false
  env:
    GITHUB_TOKEN: ***

📘 Reading input values
  
  
  
🔖 Resolve previous tag
  ℹ️ Found 57 (fetching max: 200) tags from the GitHub API for neo4j/graphql
🚀 Load pull requests
  ℹ️ Comparing neo4j/graphql - '@neo4j/graphql@2.4.0...@neo4j/graphql@2.5.0'
  ℹ️ Found 271 commits from the GitHub API for neo4j/graphql
  ℹ️ Fetching PRs between dates 2021-11-01T10:03:42.000Z to 2021-12-01T13:39:00.000Z for neo4j/graphql
  ℹ️ Retrieved 173 merged PRs for neo4j/graphql
  ℹ️ Retrieved 271 release commits for neo4j/graphql
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: ASC
  ℹ️ Used 1 transformers to adjust message
  ✒️ Wrote messages for 24 pull requests
  ℹ️ Ordered all pull requests into 3 categories
  ✒️ Wrote 18 categorized pull requests down
  ✒️ Wrote 6 non categorized pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```

Configuration below:

```json
{
    "categories": [
        {
            "title": "## 🚀 Features",
            "labels": ["feature", "graphql"],
            "exhaustive": true
        },
        {
            "title": "## 🐛 Fixes",
            "labels": ["fix", "graphql"],
            "exhaustive": true
        },
        {
            "title": "## 🧪 Tests",
            "labels": ["test", "graphql"],
            "exhaustive": true
        }
    ],
    "tag_resolver": {
        "method": "sort"
    }
}
```

**Comment by mikepenz** [comment]
Hi there @darrellwarde 

Thank you for the report. I'll have a look at this. 

Was this the current specification in your github actions? https://github.com/neo4j/graphql/commit/5020318277535ce805f848ff32c08b624fadc7fb#diff-d44dd879a02a07f5781424a643498042e49b0b3d49d2682d176d7322e89f69a6R384-R391

**Comment by darrellwarde** [comment]
> Hi there @darrellwarde
> 
> Thank you for the report. I'll have a look at this.
> 
> Was this the current specification in your github actions? [neo4j/graphql@5020318#diff-d44dd879a02a07f5781424a643498042e49b0b3d49d2682d176d7322e89f69a6R384-R391](https://github.com/neo4j/graphql/commit/5020318277535ce805f848ff32c08b624fadc7fb#diff-d44dd879a02a07f5781424a643498042e49b0b3d49d2682d176d7322e89f69a6R384-R391)

Apologies, I should have given you that as well to start with!

That's from a different workflow file, but identical YAML, the actual block is https://github.com/neo4j/graphql/blob/master/.github/workflows/release.yml#L518-L525

Thanks for the speedy response!

**Comment by mikepenz** [comment]
Oh one thing I saw based on your mono repo setup. The action offers the ability to pre-filter tags or transform tags if they are prefixed like in your case. So you can still use real `semver` ordering. 

This was showcased for example: 
https://github.com/mikepenz/release-changelog-builder-action/commit/d5c72c27f04d4eef7dd41c8423433dfa07da8e05#diff-5dd6a20ac6fda7c3a6519cec8213222616372409d92d79bc83c9e8942638d32cR52-R60

And maybe also helpful. It's possible to checkout this repo and run parts of the action locally. So you don't have to test it within the repo. This even comes with debugging support: 
https://github.com/mikepenz/release-changelog-builder-action/issues/576#issuecomment-963406744

I am currently using this branch: https://github.com/mikepenz/release-changelog-builder-action/tree/feature/605_test
And run the test via:

```javascript
npm test -- neo4j.test.ts
```

**Comment by mikepenz** [comment]
Do you possibly have an example of which PR ended up in the wrong category? 

Based on the below output it seems to at least make sense
```
    ## 🚀 Features
    
    - Feat/fulltext
       - PR: #563
    - Sorting by relationship properties for union and interface fields
       - PR: #598
    - Feat/Aggregate Sum
       - PR: #597
    - Feature/connectOrCreate
       - PR: #575
    
    ## 🐛 Fixes
    
    - Fixed edge updates on one to one relationships
       - PR: #579
    - fix/559: add subscription type fields to resolve tree field resolver
       - PR: #576
    - Querying DateTime in the edge of a connection throws an error
       - PR: #587
    - Generate scalar typedefs before extra definitions
       - PR: #599
    - Fix/564: Async error when reading from JWKS endpoint
       - PR: #578
    - Fix for missing auth parameter
       - PR: #603
    - Fix: Project All Interface Fields For Types Implementing `@relationship` Interface
       - PR: #590
    - Fix: Escape all @node directive labels
       - PR: #617
  ```

**Comment by darrellwarde** [comment]
Strange, our real output was very different! Luckily we haven't fixed the changelog yet, but it ended up like https://github.com/neo4j/graphql/releases/tag/%40neo4j%2Fgraphql%402.5.0

You can see that almost every, if not every, PR is in each category.

**Comment by mikepenz** [comment]
@darrellwarde oh, I should have looked at that earlier. It looks you are using the `v1` of the action: 
```
mikepenz/release-changelog-builder-action@v1
```
https://github.com/neo4j/graphql/blob/master/.github/workflows/release.yml#L520



If you want to use v1, this was the latest v1 README and state for the action:
https://github.com/mikepenz/release-changelog-builder-action/tree/v1.8.3

`Exhaustive` did not exist back then, as `graphql` will match for every category.

**Comment by darrellwarde** [comment]
Well now I feel like an absolute numpty! Thank you for spotting that, you've probably saved me hours of scratching my head over this.

**Comment by mikepenz** [comment]
No worries :D I didn't look at it directly either. 

Just edited my message above with some additional details. 

----

But yeah if you want to try and modify the action and configurations, it's much faster and easier if you run it locally :). So you can pre-test things without needing to tag on the repo, and wait until things run through.

**Comment by darrellwarde** [comment]
This was really great support, thank you! Pulled down that branch you pointed me to and used it to generate the correct changelogs to copy and paste in, saved me a load of time! 

Now bumped the version to `v2` and doing a release of a different product to validate. Many thanks again! 😄

**Comment by darrellwarde** [comment]
Thanks for the kind words, you have a great day too!
