### ISSUE TITLE
Missing PRs (merged PR lost) in changelog

### ISSUE THREAD

**Issue by yuhao-su** [mikepenz/release-changelog-builder-action#631]
I noticed some merged PRs which are also shown in the commits log in the main branch are not shown in the changelog.

The following info indicated fewer PRs fetched than the release commits. This rise my confusion because we are using the `squash and merge` model for our PRs, which means PRs fetched should always be equal to the commits.
```
ℹ️ Retrieved 287 merged PRs for xxx/xxxx
ℹ️ Retrieved 350 release commits for xxx/xxxx
```

**Comment by mikepenz** [comment]
@yuhao-su I see you opened a PR with the improvement to the sort order. Will look into it
