### ISSUE TITLE
Label extractor `on_property` as both body and head

### ISSUE THREAD

**Issue by titu1994** [mikepenz/release-changelog-builder-action#651]
Was just wondering if it would be possible to support the label_extractor `"on_property": "title&head"` or some similar syntax to perform the label extraction on both properties at once. Reason being, its tedious (and error prone) to have same sets of regex dealing with two different properties. For example, this is currently what I had to do - https://github.com/titu1994/NeMo/blob/changelog_builder/.github/workflows/config/changelog-config.json#L44-L152 and it works well, its just error prone. 

Pipeline result - https://github.com/titu1994/NeMo/runs/4960957329?check_suite_focus=true

**Comment by mikepenz** [comment]
Thank you for the proposal @titu1994, if I understand correctly you'd want it to run the same regex on both these properties independent, so you can save on having to specify everything twice. 

I'll have a look at this, as it is an interesting and valid usecase, especially for more advanced definitions like yours.

**Comment by titu1994** [comment]
Thanks ! There's no need for it if it requires difficult changes, but it does reduce a bit of copy pasting on my end (and more likely I'll make mistakes in the future :P)
