### ISSUE TITLE
feature request: Filter PR with certain label

### ISSUE THREAD

**Issue by maxisam** [mikepenz/release-changelog-builder-action#658]
Thanks for building this wonderful tool.

Is there is a way to filter PR with certain label?

Right Now, I use ignore_labels to do this but it is not as clear as I hope.

My use case is like this.

I use https://github.com/actions/labeler to label certain project, like `proj-a`

When I build changelog, I want to build the changelog only related to `proj-a` since the release is for `project a` in this repo.

**Comment by mikepenz** [comment]
@maxisam thank you very much. 

There could be multiple approaches to this. 

- It sounds that you have a mono-repo these issues including the discussions may be interesting for you:
  - https://github.com/mikepenz/release-changelog-builder-action/issues/566
  - https://github.com/mikepenz/release-changelog-builder-action/issues/576
  - https://github.com/mikepenz/release-changelog-builder-action/issues/605
- You may be able to use different configs based on the sub project you have.

**Comment by maxisam** [comment]
@mikepenz Thanks for the quick reply. I think #576 is what I am asking. I think I kinda agree with him. I like filter_labels better.

Here is my thought. It is like programming, KISS. I have a job for labeling. I would like another job taking care of changelog based on labels of the PR. 

However, still thank you for pointing out a solution.

**Comment by maxisam** [comment]
Just realize the exhaustive option doesn't work as good as I want.

Since I rely on output of pull_requests to determine if I should create a release. But it will take all pr into account. If there is an output for CATEGORIZED_COUNT that would be helpful.

Another issue with exhaustive is I can't have uncategorized part, but I think it is not a big deal.

**Comment by mikepenz** [comment]
@maxisam adding the `CATEGORIZED_COUNT` to the outputs is a good idea actually. 

you could maybe add a filter which collects all tickets matching the project, but don't match any other label category. So you could also show those in the changelog. 

If you have a suggestion on how to simplify such usecases further, I'd really happy to have a look.

**Comment by maxisam** [comment]
Thanks! It would be nice to have `CATEGORIZED_COUNT`.

I still think filter is the best way to go, just like how #576 suggested. 

Not sure about what you meant by simplify such usecases further. 

Do you mean the "filter" use case?

**Comment by maxisam** [comment]
Thanks!
