### ISSUE TITLE
feature request: full changelog

### ISSUE THREAD

**Issue by maxisam** [mikepenz/release-changelog-builder-action#667]
For example https://github.com/mikepenz/release-changelog-builder-action/compare/v2.8.0...v2.8.1

I think this might be useful for people, since Github's changelog has this feature

It is pretty simple. we can do it with what we have now.

However I think it will be awesome to have a Template placeholders called full_changelog_link

Thanks for the great tool again!

**Comment by mikepenz** [comment]
Oh a placeholder for the release diff. 

I love it. great proposal.
