### ISSUE TITLE
How to list unlabeled prs under a new section in the release notes?

### ISSUE THREAD

**Issue by dgokcin** [mikepenz/release-changelog-builder-action#668]
Hello and thank you for the action.

I would like to ask if that is possible to list the PRs that do not have any labels under the release notes in a section like Other Changes. How can I accomplish this?

Thanks

**Comment by mikepenz** [comment]
@dgokcin the default template for the changelog will only include all categorized PRs. 

You can fine here all possible placeholders for the template to be filled: 
https://github.com/mikepenz/release-changelog-builder-action#template-placeholders

Use these to configure the template you'd want via the configuration:
https://github.com/mikepenz/release-changelog-builder-action#configuration

For example:

```
{
    "template": "${{CHANGELOG}}\n\n<details>\n<summary>Other</summary>\n\n${{UNCATEGORIZED}}\n</details>"
}
```

**Comment by dgokcin** [comment]
Is the default template(the template applied if you do have not specified a json) located somwhere in the docs? All I want to do is keep the default settings the same with only the addition of the Others section with the unlabeled prs?

Thank you @mikepenz

**Comment by mikepenz** [comment]
@dgokcin you can provide a configuration json only with the config items you want to change. 

So you can provide a configuration with only the `template` as shown above. all the other defaults will remain. 


Just for reference, here's the set of default configuration definitions: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L52-L86

**Comment by dgokcin** [comment]
Thank you, again great action 🙏

**Comment by mikepenz** [comment]
Thank you very much.
