### ISSUE TITLE
Squashing

### ISSUE THREAD

**Issue by fazulk** [mikepenz/release-changelog-builder-action#671]
I love this package, and have been trying to make it work in an environment where everything is squashed, but haven't had luck. 

Following the GitFlow strategy so something like this

develop --> feature branch --PR--> develop > release branch --PR--> main

If I merge my PRs, everything works as intended, but if I squash, all the feature PRs are not shown in the changelog. Maybe its just not possible?

This is with the default setup.

**Comment by mikepenz** [comment]
@fazulk thank you very much for your feedback. 

Is this project open source, or do you have a sample repo with a similar history? 

I fear that the `MERGE` commit will be missing which (as far as we've found) is the only way to properly identify if a specific PR ended up within a specific release.


Here's the general order of the action:
Get PRs between a date range: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pullRequests.ts#L51-L57
Filtering out PRs not related to a release using their merge commit hash:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/releaseNotes.ts#L143-L153

**Comment by fazulk** [comment]
@mikepenz this is the repo i'm working in https://github.com/fazulk/test-repo

Yeah, I think your right, there is no real way of getting around it unless i merge. 

One thing i noticed, is when i DO **merge** from release into main, the PRs that didn't show up in the previous release (**which was squashed**), now show up. Maybe i'm not completely understanding the release process. See below:
![Screen Shot 2022-02-03 at 2 04 34 PM](https://user-images.githubusercontent.com/21964900/152437029-73e990db-984b-45d1-bf75-b4d3c1225359.png)

**Comment by mikepenz** [comment]
@fazulk in your sample with the squashed PR it finds the PR but as it has no `label` it will go into the uncategorised section:
https://github.com/fazulk/test-repo/pull/19

<img width="901" alt="Screenshot 2022-02-04 at 08 35 14" src="https://user-images.githubusercontent.com/1476232/152489853-623f0038-cb70-4b85-84d7-284f7340969b.png">

Here is a short test case to test this out.

**Comment by fazulk** [comment]
Thanks! Yeah, i did not add a label to the `release` branch. Otherwise It probably would have shown up there. I think everything is working as intended.

**Comment by mikepenz** [comment]
Glad everything works as expected. I think this can be closed in this case.
