### ISSUE TITLE
Building changelog fails on double quote in a commit message

### ISSUE THREAD

**Issue by antongoncharov-ingka** [mikepenz/release-changelog-builder-action#676]
The action fails when there's a `"` character somewhere in commit messages or PR names. The error message is `conditional binary operator expected`.

It occurs in an auto-generated block:
```sh
if [[ "false" == "true" || "## What’s Changed

// a commit message string containing double quote, e.g.: 
// feat: implemented "hello world"

" == "no changes" ]]; then
    exit 1
fi
```

The changelog config json:
```json
{
  "sort": "DESC",
  "template": "## What’s Changed\n\n${{UNCATEGORIZED}}",
  "pr_template": "* ${{TITLE}} (#${{NUMBER}})",
  "empty_template": "no changes"
}
```

The expected behavior here is to have double quotes automatically escaped.

**Comment by mikepenz** [comment]
@antongoncharov-ingka just to ensure I fully understand.

You are using the result of the changelog builder action within a bash script in a follow up step?

I am not sure if the action should be responsible to change the output for bash scripts. After all the action properly reflects the expected output (as the input did contains those characters). 


It looks you are actually trying to identify if there have been any changes. Post action run. 

This can also be achieved by checking if `outputs.categorized_prs` and `outputs.uncategorized_prs` contains no PRs. (in your case maybe even only the categorized ones?

**Comment by antongoncharov-ingka** [comment]
@mikepenz You're right, that's my misunderstanding, I initially thought this step was embedded into the plugin. This issue may be closed, I agree with you that it should be escaped externally.
