### ISSUE TITLE
Possible to Avoid Duplicate Categorization?

### ISSUE THREAD

**Issue by mcbridesedai** [mikepenz/release-changelog-builder-action#681]
This action has been so helpful - thank you for building it! 

I'm new to the world of actions, hopefully this is the right way to ask this question.

I was wondering, is there a way to have a PR that has two valid category labels to only show up in one category in the changelog instead of both? 
For example, if a PR has a label for a Breaking Change as well as a Feature, could it only show up in the Breaking Change category of the changelog and not also in the Feature category? 

Thank you again!

**Comment by mikepenz** [comment]
Thank you very much @mcbridesedai 

Yes this is the right place to raise questions / issues / ...

Right now there is no such way, as this would require some sort of strict ordering of labels. E.g. which of the labels has higher priority and then only match the first.

Thinking of what could be the most flexible yet simple solution around this.

**Comment by mcbridesedai** [comment]
Thank you for such a quick reply, @mikepenz!
Okay, no worries. Always good to know I wasn't just missing something 😊 If you think of anything, let me know! But I'll close this issue for now. 
Again - thank you for making such a helpful, thoughtful action.

**Comment by mikepenz** [comment]
v2.9.0 is released with a new configuration option. `exclude_labels` 

E.g. this allows you now to define that the `Feature` won't include any PRs with the label `Breaking Change`

**Comment by mcbridesedai** [comment]
@mikepenz  - that's amazing! Thank you so much for making those updates! 🙌
