### ISSUE TITLE
How to write  a duplicate_filter to remove the exactlly same one

### ISSUE THREAD

**Issue by fabian4** [mikepenz/release-changelog-builder-action#682]
As I use it in the commit mode，how to write  a duplicate_filter to remove the exactlly same commits and remain the unique one.

**Comment by mikepenz** [comment]
Hello. 

There are 2 testcases which do de-duplication:
https://github.com/mikepenz/release-changelog-builder-action/blob/8e61f769fc464aeab3aea641a6f34b0b3d40e3c1/__tests__/transform.test.ts#L367-L412

The feature is meant to allow you retrieve some form of identifier given the commits which then merges thing together. 

The tests do not have have it in commit mode. 

Is the respective repo open source?

**Comment by fabian4** [comment]
For example I have 3 commit below
~~~text
fix: fix a bug
fix: fix a bug
feat: upgrade
~~~
and I want to have
~~~text
fix: fix a bug
feat: upgrade
~~~

**Comment by mikepenz** [comment]
If you have a deduplication which uses the full name as id that could work for exact matches:
```xml
    "duplicate_filter": {
      "pattern": ".+",
      "on_property": "title",
      "method": "match"
    },
```

**Comment by fabian4** [comment]
That is all I need !
Thanks a lot for your time
