### ISSUE TITLE
How to use label extractor to replace a label ?

### ISSUE THREAD

**Issue by iabdalkader** [mikepenz/release-changelog-builder-action#701]
Hello, is it possible to use the label extractor's `replace` and `target` to replace a matched pattern with a new label ? For example, would the following config replace `examples` with `scripts` and then sort it in a category with `"labels": ["scripts"]` ? If not, then what is the purpose of `replace` and `target` ?

```
      {
        "pattern": "^examples",
        "method": "replace",
        "target": "scripts",
        "on_property": "title"
      },
```

**Comment by mikepenz** [comment]
The label extractor is meant to extract additional labels from a PR. So if you did not define labels on the PR in git, but instead have some identification in PR titles or the PR description. 

label_extractor | An array of Extractor specifications, offering a flexible API to extract additinal labels from a PR (Default: body, Default in commit mode: commit message).
-- | --
label_extractor.pattern | A regex pattern, extracting values of the change message.
label_extractor.target | The result pattern. The result text will be used as label. If empty, no label is created. (Unused for match method)
label_extractor.on_property | The property to retrieve the text from. This is optional. Defaults to: body. Alternative values: title, author, milestone.
label_extractor.method | The extraction method used. Defaults to: replace. Alternative value: match. The method specified references the JavaScript String method.
label_extractor.flags | Defines the regex flags specified for the pattern. Default: gu
label_extractor.on_empty | Defines the placeholder to be filled in, if the regex does not lead to a result.

Here's a test case for example. It extracts labels from the title: 
https://github.com/mikepenz/release-changelog-builder-action/blob/e566ac58d748e37369bd98a4d1ddd1381ef208a2/__tests__/transform.test.ts#L109-L131

**Comment by mikepenz** [comment]
The `method` describes the respective functionality from javascript. if the regex is inserted into a `replace` or a `match` operation: https://github.com/mikepenz/release-changelog-builder-action/blob/e566ac58d748e37369bd98a4d1ddd1381ef208a2/src/transform.ts#L404-L414

The `target` is the pattern in which the value is inserted. giving additional flexibility to modify the values

**Comment by iabdalkader** [comment]
Thanks for the detailed reply, and for pointing out the relevant code. I think I see what I did wrong, the pattern I used didn't match the whole string and only replaces the matched part.
