### ISSUE TITLE
Ability to use refs/pull/# instead of tag

### ISSUE THREAD

**Issue by ThePieMonster** [mikepenz/release-changelog-builder-action#703]
I have a repo where the Releases themselves are tagged upon creation but no tags are used before hand.

Can we have a feature implmented that can look at `refs/pull/n-1` to `refs/pull/n` and gather the same data?

```
Run mikepenz/release-changelog-builder-action@v1
  with:
    ignorePreReleases: false
    failOnError: false
    commitMode: false
  env:
    APP_NAME: XXX
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-101/x64
    VERSIONNAME: [2](https://github.com/ThePieMonster/XXX/runs/5470140862?check_suite_focus=true#step:8:2).0.[4](https://github.com/ThePieMonster/XXX/runs/5470140862?check_suite_focus=true#step:8:4)
    GITHUB_TOKEN: ***

📘 Reading input values
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 12[8](https://github.com/ThePieMonster/XXX/runs/5470140862?check_suite_focus=true#step:8:8)

```

**Comment by mikepenz** [comment]
@ThePieMonster instead of the `tag` you can also use the SHA1 git hash, which should serve as a more flexible solution compared to the `refs/pull/`.

**Comment by ThePieMonster** [comment]
@mikepenz Included the below code in the Checkout code step which got me a little further. 
```
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

The last submitted tag that was created upon Release was 2.0.3 in this case. The current build is 2.0.4. I can manually pass this new number as a parameter but the `mikepenz/release-changelog-builder-action@v1` still thinks 2.0.3 is the latest it seems.

![image](https://user-images.githubusercontent.com/11359134/157332067-4565f82d-7572-4787-a9d4-4d6a2b9e4061.png)
![image](https://user-images.githubusercontent.com/11359134/157332238-8f544f70-2235-4bce-b67f-7cf0d1e5c670.png)

**Comment by ThePieMonster** [comment]
@mikepenz Got the "create tag" GitHub script to create a tag and pass it through. The build is running as part of a PR (check before a merge) but shows that no PRs are found. Any idea as to why?

![image](https://user-images.githubusercontent.com/11359134/157339921-b3a7c0cd-a691-4b9f-9090-a947609a8dad.png)

**Comment by mikepenz** [comment]
The action allows to specify from and to tag as either the git `tag` or the `SHA-1` git hash. There is currently no direct plan to allow it take branches instead. 

You can have build steps before this action to retrieve the SHA-1 for a branch if your usecase requires this. 

Please also note that generally this action is meant to get release notes for releases (and the respectively merged PRs) which should have specific assigned states.
