### ISSUE TITLE
Format line

### ISSUE THREAD

**Issue by hannesa2** [mikepenz/release-changelog-builder-action#711]
Hi, thank you for the action !
I want to ask if it's possible to have pull request number in the **same line** (to compact output) like this

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3314607/159416749-9b2417aa-cda3-4ba7-86db-0816d6d933e2.png">

**Comment by mikepenz** [comment]
Hello @hannesa2 

Yes that's possible. By default the following template is used per PR: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L60

You need to provide a custom configuration json to the action with the adjusted format: https://github.com/mikepenz/release-changelog-builder-action#configuration

If you want to keep everything else default the following will be enough:

```
{
    "pr_template": "- ${{TITLE}} #${{NUMBER}}"
}
```
