### ISSUE TITLE
How to use RELEASE_DIFF template placeholder

### ISSUE THREAD

**Issue by dgokcin** [mikepenz/release-changelog-builder-action#717]
Hello

I could not figure out how to use RELEASE_DIFF placeholder. Could you please tell me what am I be missing?

![image](https://user-images.githubusercontent.com/33603535/160244439-8064b7f9-5b15-4fcb-b1f3-877ac51cd507.png)
![image](https://user-images.githubusercontent.com/33603535/160244454-d8ed06d1-fdf1-4c93-a8c4-c873fa4362ee.png)

Thanks

**Comment by mikepenz** [comment]
@dgokcin were there any changes in the diif (e.g. PRs which should have been included?) 
If not the empty template is used: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L9

**Comment by dgokcin** [comment]
@mikepenz my bad, the empty template was used indeed. thanks
