### ISSUE TITLE
Feature request: ${{REVIEWERS}} is empty for reviewers who approved a PR

### ISSUE THREAD

**Issue by thedmeyer** [mikepenz/release-changelog-builder-action#720]
In my implementation of the action, I am only seeing reviewers show up for PRs that include reviewers who did not respond prior to the PR in question being merged.

**Comment by mikepenz** [comment]
Interesting. You don't by coincidence have used this on an open source repo, which I could try to use locally?

**Comment by mikepenz** [comment]
Hmmm so I tried to reproduce this. and you are right. after requiring myself as being a requested reviewer. I won't show up if I approve the PR: 
https://api.github.com/repos/mikepenz/release-changelog-builder-action/pulls/718


For another PR where I only requested myself but didn't approve I will show up:
https://api.github.com/repos/mikepenz/release-changelog-builder-action/pulls/712


This looks to be a limitation of the GitHub API. I don't see a different field which would expose users who did approve the PR.

**Comment by mikepenz** [comment]
Looks this has to be done via a special endpoint: 

https://stackoverflow.com/a/41700165/325479

**Comment by mikepenz** [comment]
So the reviewers will require this call: https://api.github.com/repos/mikepenz/release-changelog-builder-action/pulls/716/reviews

I'll need to investigate the feasibility of adding this, as it may result in a significantly increased amount of API requests.

**Comment by mikepenz** [comment]
You can find a first version of this supported here: https://github.com/mikepenz/release-changelog-builder-action/pull/728
