### ISSUE TITLE
Looks like duplicate_filter is not being recognized in config

### ISSUE THREAD

**Issue by MichalWasowskiMeniga** [mikepenz/release-changelog-builder-action#756]
Hello,

I'm trying to setup `duplicate_filter` to strip duplicates from the PR list that the Builder retrieves.

Lets say my PR list looks like this:
```
TEST-123: First awesome PR
TEST-123: Another awesome PR
```

In the result I am stripping the message and leaving only `TEST-XXX` using transform:
```
    "transformers": [
      {
        "pattern": "((?:TEST|Test))[ -](\\b\\d{3,4}\\b).*",
        "target": "$1-$2 - "
      }
    ]
```
To remove duplicates I added `duplicate_filter`:
```
    "duplicate_filter": {
      "pattern": "(?:(?:TEST|Test))[-](?:\\b\\d{3,4}\\b)",
      "on_property": "title",
      "method": "match"
    }
```
But I am still getting:
```
TEST-123
TEST-123
```

I looked at the implementation and I see that it should do the deduplication before applying transform:
```
    if (config.duplicate_filter !== undefined) {
        const extractor = validateTransformer(config.duplicate_filter);
        if (extractor != null) {
            core.info(`ℹ️ Remove duplicated pull requests using \`duplicate_filter\``);
            const deduplicatedMap = new Map();
            const unmatched = [];
            for (const pr of prs) {
                const extracted = extractValues(pr, extractor, 'dupliate_filter');
                if (extracted !== null && extracted.length > 0) {
                    deduplicatedMap.set(extracted[0], pr);
                }
                else {
                    core.info(`  PR (${pr.number}) did not resolve an ID using the \`duplicate_filter\``);
                    unmatched.push(pr);
                }
            }
            const deduplicatedPRs = Array.from(deduplicatedMap.values());
            deduplicatedPRs.push(...unmatched); // add all unmatched PRs to map
            const removedElements = prs.length - deduplicatedPRs.length;
            core.info(`ℹ️ Removed ${removedElements} pull requests during deduplication`);
            prs = (0, pullRequests_1.sortPullRequests)(deduplicatedPRs, sortAsc); // resort deduplicatedPRs
        }
        else {
            core.warning(`⚠️ Configured \`duplicate_filter\` invalid.`);
        }
    }
```
An in my GH action I see:
![obraz](https://user-images.githubusercontent.com/83703296/167865280-a820ec3f-81ef-4e05-8e0e-002315bc6a0c.png)
So it looks like it's not even picking up the `duplicate_filter` section since it's not outputing any messages that are defined inside the top most if?

Any ideas?

Thanks in advance :)

Kind regards,
Michal

**Comment by mikepenz** [comment]
Thank you for the report. I'll need to have a deeper look into this. 

There's a testcase checking de-duplication to work: https://github.com/mikepenz/release-changelog-builder-action/blob/79a53b0d88fd38508be1ee73dbc2737f73838910/__tests__/transform.test.ts#L408-L431

Will report back if I need more information. Is the repository open source which you tested towards? (in this case I could reproduce what you see 1:1) otherwise I'll need to mock a similar setup

**Comment by MichalWasowskiMeniga** [comment]
Hi @mikepenz!

Thanks for such fast reply. No, sadly it isn't. I might mock something up if there will be problems reproducing it :)

Michal

**Comment by MichalWasowskiMeniga** [comment]
@mikepenz Were you able to reproduce it on your end?

**Comment by mikepenz** [comment]
@MichalWasowskiMeniga I sadly haven't had the chance yet to look further into it, between Google IO and work. I hope I may be able to spend some time with it tomorrow

**Comment by MichalWasowskiMeniga** [comment]
@mikepenz Ok, does it make any difference that we're not categorizing PRs and all of ours are treated as uncategorized? Full config is:
```
{
    "sort": "ASC",
    "template": "# Overview  🚀\n# Release notes\n${{UNCATEGORIZED}}",
    "pr_template": "${{TITLE}}",
    "empty_template": "No changes",
    "duplicate_filter": {
      "pattern": "\\[ABC-....\\]",
      "on_property": "title",
      "method": "match"
    },
    "max_pull_requests": 1000,
    "max_back_track_time_days": 1000
}
```

**Comment by MichalWasowskiMeniga** [comment]
@mikepenz Added you as collaborator :)

**Comment by mikepenz** [comment]
> Run mikepenz/release-changelog-builder-action@v1

I think I found the issue. Your screenshots did not include the version you are using. But looks you are using `v1` which is not having a lot of the features the new v3 already offers

Find v1 capabilities here: https://github.com/mikepenz/release-changelog-builder-action/tree/v1

**Comment by mikepenz** [comment]
(updated the README to v3, sorry for this. Forgot that there is a section beside: https://github.com/mikepenz/release-changelog-builder-action#setup which references a specific version)

**Comment by MichalWasowskiMeniga** [comment]
I feel so dumb :D I swapped `v1`->`v3` and it works 💪 

Thank you so much for assistance! And with sorting this is now perfect :)

**Comment by mikepenz** [comment]
Your last run is basically working. You also need to adjust there for `ABC`, but after that it will also handle that if I run this test locally :) 
`(?:(?:TEST|Test|ABC|abc))[-](?:\\b\\d{3,4}\\b)` 

Glad things work now. Thank you for providing the additional demo repo to pin it down

**Comment by MichalWasowskiMeniga** [comment]
Naah, ABC was only added per your request to test with the pattern you have in the tests.

Last thing. Any idea why if I use `i` parameter in the regex it doesn't work at all? For example:
`((?i:test)(?-i))[ -](\\b\\d{3,4}\\b).*`
Should match `test` case insensitive, but I am getting
```
Update Program.cs
Test-222: Add release config
Test-312: Adding release notes update
Update Program.cs
TEST-681-Adding-removing-duplicates
ABC-1234: First one
ABC-1234: Second one
```
so like the transform was not applied at all 🤔

**Comment by mikepenz** [comment]
@MichalWasowskiMeniga that goes beyond my understanding of regex, maybe Node16 or javascript does not like this notation. 🤔

**Comment by mikepenz** [comment]
<img width="510" alt="Screenshot 2022-05-13 at 16 18 45" src="https://user-images.githubusercontent.com/1476232/168303645-a8e5eb13-098b-43c4-8010-076e5170d3cc.png">

Seems the regex is not supported by JavaScript - https://regexr.com/

**Comment by MichalWasowskiMeniga** [comment]
That's fine, I just did
```
(?:(?:TEST|Test|test))[-](?:\\b\\d{3,4}\\b)
```
Sometimes PR names get some strange case conversion depending where/how are they pushed.

Thanks for the help again 👍

**Comment by mikepenz** [comment]
@MichalWasowskiMeniga you can pass `flags` as part of the filter
```
"duplicate_filter": {
  "pattern": "\\[ABC-....\\]",
  "on_property": "title",
  "method": "match",
  "flags": "gu" 
}
```
(`gu` is used by default)

**Comment by mikepenz** [comment]
Oh, topic switched from `duplicate_filter` :D you may want to open a feature suggest as new ticket for that part for the transformers :)

**Comment by MichalWasowskiMeniga** [comment]
Oh yeah, sorry for that 😊 

And done https://github.com/mikepenz/release-changelog-builder-action/issues/761
