### ISSUE TITLE
Is there a way to get `No changes` per category specified using labels?

### ISSUE THREAD

**Issue by MichalWasowskiMeniga** [mikepenz/release-changelog-builder-action#804]
Hi again Mike :)

I was able to get some time to present ability to automatically categorize pull requests in release notes using your tool based on labels.

We haven't been using them before (go figure) but I think this would help us a lot to automate things.

My categories section looks like this:
```
  "categories": [
    {
      "title": "# Release notes",
      "labels": ["enhancement", "bug", "documentation", "infrastructure", "dependency"]
    },
    {
      "title": "# REST API Changes",
      "labels": ["api-change"]
    }
  ]
```

If I have a pull request with `api-change` label, release notes look like this:

**Release notes**

ABC-123-[text] 
TEST-123-[text] 

**REST API Changes**

TEST-321-[text] 

But if i don't, I get:

**Release notes**

ABC-123-[text] 
TEST-123-[text] 

When I would expect something like:

**Release notes**

ABC-123-[text] 
TEST-123-[text] 

**REST API Changes**

No changes.

Is it possible and I'm just blind and can't seem to find it in configuration?

Kind regards,
Michal

**Comment by mikepenz** [comment]
Hi @MichalWasowskiMeniga 

Given that this is an open source project I develop in my free time I sadly can't give an estimate. But sooner than later :D

**Comment by mikepenz** [comment]
Please see the new per category configuration allowing you to provide an empty content. this can be controlled per category:
<img width="411" alt="Screenshot 2022-07-08 at 11 08 44" src="https://user-images.githubusercontent.com/1476232/177958635-f132859d-4308-4f5d-aeb8-145c2d3ea33b.png">

**Comment by MichalWasowskiMeniga** [comment]
You are a legend Sir <3

Thank you!
