### ISSUE TITLE
Add link to the title by some of regex 

### ISSUE THREAD

**Issue by johnico** [mikepenz/release-changelog-builder-action#829]
hello 
i read this issue https://github.com/mikepenz/release-changelog-builder-action/issues/389 
i m trying to add Jira ticket to the pr title 

the link above does not works for me , there is no link and there is 2 lines for each PR 
smth like :

I am already make sure the title is in the desier format by kind of lint the title when pull request is open , but also i will need support for a free title.

* [JIRA-123] 123 test
* PR: #1

i would like to achieve smth like:  

* [JIRA-123] descrription prnum
* free title pr num    - without any link
*  [JIRA-444] descrription 2  prnum

and with a link to the jira 

is it possible ?
 
thanks

**Comment by mikepenz** [comment]
Yes that's definitely possible. Personally I tend to have some alternative title for cases which won't have a ticket. like: `[CI]` or similar. 

What's worth noting. the `transformer` is applied on the PR content *after* the general structure for the single PR message was defined. 

So for example a PR format like below (resulting in one line having the title, and in the second like the PR Nr.)
This is then put through the transformer, which will restructure it to have:

```
- PR TITLE - FIX JIRA-Link | PR Nr
```
 
```
{
  "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
  "transformers": [
    {
      "pattern": "[-\\*] (\\[([J].+?)\\])(\\[(.+?)\\])?( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $6  - FIX https://jira.atlassian.net/browse/$2 | $8"
    },
    {
      "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $4  - $6"
    }
  ]
}
```

**Comment by johnico** [comment]
@mikepenz  thanks for the support
my titles are.  [JIRA-123] 123 test. or  a free title

i tried your suggestion and i got nice format

[JIRA-123] ttt
 * pr
 
 but without the line 
 
 
 and i m also wants to keep the []

**Comment by johnico** [comment]
@mikepenz  ok i managed to do it with : 
```
    {
      "pattern": "[-\\*] (\\[([R].+?)\\])(\\[(.+?)\\])?( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "[[$2](somelink/$2)] - $6 | $8"
    },
    ```
    
    the result is great
thanks

**Comment by mikepenz** [comment]
That's great.

**Comment by johnico** [comment]
@mikepenz  one thing

about free text
its print the default template 

how can i make sure that if there is no Jira-XXX so just print the same template without a link. ; "free text | PR"

**Comment by mikepenz** [comment]
@johnico you could have a different transformer handling these cases for example. 

Btw. check out this section: https://github.com/mikepenz/release-changelog-builder-action#local-testing- allowing you to execute the action locally, not requiring you to do changes on the repo over and over again
