### ISSUE TITLE
Label Extraction based on Branch Name?

### ISSUE THREAD

**Issue by cnuss** [mikepenz/release-changelog-builder-action#830]
Greetings!

Is there a way to do Label Extraction based on a PR's original branch name? Our branches are named `fix/blah-blah` or `feat/blah-blah` etc.

Happy to attempt a PR if this is a needed feature, so let me know!

**Comment by mikepenz** [comment]
Hello. 

Thank you so much for this great question. 
Right now this is not yet supported, and we actually did not keep the branch name of PRs yet. 

Did a quick test to add that: https://github.com/mikepenz/release-changelog-builder-action/pull/831
You should be able to try it out by using the following ref `c4a63d86ad980402cd8a9590bcc65877784bdb62` (from this PRs commit) as version

**Comment by cnuss** [comment]
Thanks for the ultra fast turnaround @mikepenz ... trying this now!

**Comment by cnuss** [comment]
Worked like a charm, thank you!

Used the following config:

```
{
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": ["feat"]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": ["fix"]
    },
    {
      "title": "## 🧪 Experimental",
      "labels": ["experimental"]
    },
    {
      "title": "## 📦 Uncategorized",
      "labels": []
    }
  ],
  "sort": {
    "order": "ASC",
    "on_property": "mergedAt"
  },
  "label_extractor": [
    {
      "pattern": "(.*)/(.+)",
      "on_property": "branch",
      "target": "$1",
      "flags": "gu"
    }
  ],
  "template": "${{CHANGELOG}}",
  "pr_template": " - *#${{NUMBER}}* ${{TITLE}} [@${{AUTHOR}}]",
  "empty_template": "- no changes",
  "max_pull_requests": 1000,
  "max_back_track_time_days": 1000
}
```

<img width="1235" alt="Screen Shot 2022-07-27 at 11 45 09 AM" src="https://user-images.githubusercontent.com/819991/181291137-ca7876f1-9b38-4ce3-915b-e37e9facc8c4.png">

**Comment by mikepenz** [comment]
@cnuss thank you for testing it. 

The PR will still need updates on the tests before I'll get it merged, but it will get into the next release. 

As I am currently still wrapping up some items for the next release, it may be a bit more time than usual. 

You can stay on the pinned commit though until then :) (using the full length ref is anyways advised from a sec perspective :D)

**Comment by cnuss** [comment]
no worries! thanks again!

the pinned commit is good enough for now til you finish, I'll stay subscribed here for updates

**Comment by mikepenz** [comment]
It's tagged now as `v3.2.0-rc02`
