### ISSUE TITLE
Unexpected input(s) 'configurationJson'

### ISSUE THREAD

**Issue by shahnozaAI** [mikepenz/release-changelog-builder-action#839]
I am not sure how to pass configurationJson, as the action outputs a warning and generates a changelog in default format:
![image](https://user-images.githubusercontent.com/98027125/181825986-9c10985d-a2ca-43e4-bc55-6efa6455fd46.png)

My settings are:

```      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: "${{ steps.bump-version.outputs.version }}"
        with:
          configurationJson: |
            {
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feature"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                }
              ],
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "pr_template": "- #{{TITLE}} PR: ##{{NUMBER}}",
              "empty_template": ""
            }
```

**Comment by mikepenz** [comment]
This feature is currently only available on the `v3.2.0-rc02` tag: https://github.com/mikepenz/release-changelog-builder-action/releases/tag/v3.2.0-rc02

Please find the README for v3.1.1. here: https://github.com/mikepenz/release-changelog-builder-action/tree/v3.1.1

**Comment by shahnozaAI** [comment]
Thank you, I changed the version, and the warning is gone! However, I am still not able to generate the template, maybe I am using the version too early? 

![image](https://user-images.githubusercontent.com/98027125/181834799-40c4f2e6-5032-43ea-92a6-afb7c7db9f3c.png)

**Comment by mikepenz** [comment]
@shahnozaAI it seems between those 2 versions you have 3 commits. 


do you use the action in `commitMode`? or based on `PR`s? 

It seem's that maybe there have been no PRs merged between those two tags?

**Comment by shahnozaAI** [comment]
This is the output from the above run, so it does see the latest merged PR between tags, but doesn't pick up the custom template. I did not specify the mode. 

![image](https://user-images.githubusercontent.com/98027125/181835928-9c9d7f67-48fc-477c-9904-6f41c0d1339f.png)

**Comment by shahnozaAI** [comment]
I can see the `commitMode: false`

![image](https://user-images.githubusercontent.com/98027125/181836499-fb56a6a1-245c-4311-a770-54fcbbc8d524.png)

**Comment by mikepenz** [comment]
@shahnozaAI thank you, I misunderstood you initially. I thought no PRs would be shown. 

The Content you see in the release does not look like it was generated by this action. 

The `release-changelog-builder-action` will only generate the content for the release, but it would require a step afterwards which assigns it to a release. 

similar like here: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L139-L153

**Comment by shahnozaAI** [comment]
Thanks a lot for all the prompt replies, you are right! Another action was generating default output and rewriting it even with the passed output from `release-changelog-builder-action`.
