### ISSUE TITLE
Action is not getting failed to run if some error occurs

### ISSUE THREAD

**Issue by KausarNaqvi** [mikepenz/release-changelog-builder-action#883]
![image](https://user-images.githubusercontent.com/106592880/187088920-9e7e181f-0f7e-4a61-8782-6ba24a8985c2.png)
![image](https://user-images.githubusercontent.com/106592880/187088986-70a68fe8-d58f-437b-9e08-19bd22a2952f.png)

- The attached screenshot shows that, an error occured because of an invalid tag (that does not exist) passed as "toTag" param. 
- In the second image you can see I set the failOnError as true. But it did not stopped the action. The action kept on running.

**Comment by mikepenz** [comment]
@KausarNaqvi as you can see in your log above the configuration was provided, but it couldn't be parsed. Which results in it falling back to the default:
<img width="453" alt="Screen Shot 2022-08-28 at 21 22 26" src="https://user-images.githubusercontent.com/1476232/187090978-97b07e49-f31e-420f-9c0d-f826e806be9d.png">

In your config it looks you have an invalid json. The last item in an array has a `,` after it. which is looks to be the issue. 

<img width="224" alt="Screen Shot 2022-08-28 at 21 23 07" src="https://user-images.githubusercontent.com/1476232/187091009-a802c11e-948a-4ce0-a863-41fe68418433.png">
 
Remove the `,` and make sure the full json is a valid json. (you can see in the log if it was able to parse it

**Comment by mikepenz** [comment]
@KausarNaqvi the `failOnError` configuration is part of the top level configurations, and not part of the `json`. 


https://github.com/mikepenz/release-changelog-builder-action/blob/8dddfc270f05157a486c35bdd239e1823f008531/action.yml#L28-L30

**Comment by KausarNaqvi** [comment]
@mikepenz my bad! Thanks for the swift reply. I am gonna fix this in my workflow.
