### ISSUE TITLE
a configuration to strip whitespaces?

### ISSUE THREAD

**Issue by scarf005** [mikepenz/release-changelog-builder-action#929]
`${{TITLE}}` in
```json
"pr_template": "- PR: #${{NUMBER}} **${{TITLE}}** by ${{AUTHOR}}",
```
often does not get bold because of leading or trailing whitespaces. could there be a configuration to strip remaining whitespaces?

**Comment by mikepenz** [comment]
@scarf005 thank you for the ticket. That's an interesting note. 

Generally I'd say the authors of PRs should ensure there are no whitespaces before and after - as it comes back to PR etiquette to spend the appropriate time to have these nicely. 

That being said though, while there is no "simple" flag to trail whitespaces, there are various utils provided as part of the configuration which offer multiple ways to modify the content. 

While the normal transformers could be used, it's fair that these are not the most fitting for the request. 

Instead the new feature of `CUSTOM_PLACEHOLDER`s (which is still experimental - but stable) can be used. 

An example can be found here: https://github.com/mikepenz/release-changelog-builder-action#experimental-

This allows you to define a custom placeholder, for example `STRIPPED_TITLE` - and then an associated regex extracting the text with the whitespaces removed. Some regex like `(([\S]+[\s]*)*[\S]+)` (https://regexr.com/321iv)

**Comment by mikepenz** [comment]
Looked some more into this. 

So while the `custom_placeholder` feature itself would be the right way to go for this request, it seems that the current variant of the regex usage for these may not match the requirement fully. 

Given that currently it would use a `value.replace(transformer.pattern, transformer.target)` condition to extract a value. 

And if there are no whitespaces that may not return any data - https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L340

It's probably worth to explore on expanding the flexibility of the placeholder to also cover cases like yours.

**Comment by mikepenz** [comment]
As noted in my previous message, there needs to be a change to fully handle your case. Which would be done in this PR: https://github.com/mikepenz/release-changelog-builder-action/pull/933 (given that this may change behaviour, I can't say for certain yet when this may land in a release) - in any way you can use that particular commit for the time 

Additionally here is a small test-case for the specific custom placeholder: https://github.com/mikepenz/release-changelog-builder-action/blob/9a9874ae0a080b834fd92a2207cdf34be0e6665f/__tests__/transform.test.ts
