### ISSUE TITLE
Error while running action: API rate limit exceeded for user ID XXXXX609

### ISSUE THREAD

**Issue by RobinMaronier** [mikepenz/release-changelog-builder-action#948]
Hello,

i'm getting an error while running this action.
I'm using this action since long time now and only today I have this error : `API rate limit exceeded for user ID 66129609`

Action : `mikepenz/release-changelog-builder-action@v3.3.1` (this version already works before)

Any ideas ?
Thanks !

**Comment by mikepenz** [comment]
Good day. 

The action uses the `github API` via the github packages. Depending on the used token and your environment. Please see the following rate limits from GitHub: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

There is a rate limit API you can use to check the current available limit for your user: https://docs.github.com/en/rest/rate-limit

**Comment by mikepenz** [comment]
Can you please report back on this issue?

Please note that the action can not adjust your rate limit and it is required that the provided token can be used to make the respective API calls

**Comment by RobinMaronier** [comment]
Sorry for the non-answer. It seems that it's not an issue on your side. I will check rate limit on mine 😄 
Thanks for your time !

**Comment by mikepenz** [comment]
Thank you for reporting back.
