### ISSUE TITLE
Action picks `toTag` as `fromTag` leading to an empty diff

### ISSUE THREAD

**Issue by tgolsson** [mikepenz/release-changelog-builder-action#954]
Hey!

I'm not sure if there's a misconfiguration issue on my end; but when running here: https://github.com/tgolsson/pants-backend-mdbook/actions/runs/3448669658 there should have been 1 documentation PR picked up. However; the `fromTag` picked up being the same as the ref we're running for:

```
Run mikepenz/release-changelog-builder-action@v3.4.0
  with:
    toTag: refs/tags/v0.1.1
    configuration: .github/workflows/changelog.json
    includeOpen: false
    ignorePreReleases: false
    failOnError: false
    fetchReviewers: false
    fetchReleaseInformation: false
    commitMode: false
  env:
    PY: python echo PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==.*']
    PANTS_CONFIG_FILES: pants.ci.toml
    GITHUB_TOKEN: ***
📘 Reading input values
  ℹ️ Configuration successfully loaded.
🔖 Resolve tags
  ℹ️ Found 2 (fetching max: 200) tags from the GitHub API for tgolsson/pants-backend-mdbook
  🔖 Resolved previous tag (v0.1.1) from the tags git API
🚀 Load pull requests
  ℹ️ Comparing tgolsson/pants-backend-mdbook - 'v0.1.1...refs/tags/v0.1.1'
  ℹ️ Found 0 commits from the GitHub API for tgolsson/pants-backend-mdbook
```

The previous tag should have been 0.1.0. I'm already doing an unshallow step earlier:

```
Run git fetch --prune --unshallow --tags
  git fetch --prune --unshallow --tags
  shell: /usr/bin/bash -e {0}
From https://github.com/tgolsson/pants-backend-mdbook
 * [new branch]      main       -> origin/main
 * [new tag]         v0.1.0     -> v0.1.0
```

I'm wondering if the fact that it uses `refs/tags/v0.1.1` on the upper end means one should use `github.ref_name` instead of `github.ref` as the toTag?

**Comment by mikepenz** [comment]
@tgolsson thank you very much for the report. Sorry for the late reply. 

Your note on the bottom is correct. You want to only pass `v0.1.1` as the `toTag` -> e.g. the tag name. 

You can actually also drop the `toTag` completely in your case as the default of the action will use the `ref`. 
By default it will first to by the `ref` of the github context:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/tags.ts#L182-L202
If it identifies it to be a tag, it will get only the tag name 

In case the ref is not a tag, it will as an alternative use the latest tag from your repository.

**Comment by mikepenz** [comment]
I hope the above answer helped. If not please report back to re-open.

**Comment by tgolsson** [comment]
It did, thank you! Wanted to maybe PR a doc clarification but haven't found time for it.
