### ISSUE TITLE
bug: labels can be empty

### ISSUE THREAD

**Issue by eXponenta** [mikepenz/release-changelog-builder-action#965]
Follow:

https://github.com/mikepenz/release-changelog-builder-action/blob/d77f10180b6b7642919aab9f970e75f6ee07f0cb/src/transform.ts#L486

if i will use a `^(\w+)(\s*\(.+\)\s*)?\s?:\s*(.+)`

second math can be `undefined`

see:
https://regex101.com/r/vPYrcr/1

**Comment by mikepenz** [comment]
@eXponenta thank you for the report. 

I am not sure I follow. If the regex does not result in a match and the `labels` array is empty, then it wouldn't return a value here. which is the expected behaviour. 

do you have a more complete example or test-case which shows this behaviour?

**Comment by eXponenta** [comment]
if you will use a ` ^(\w+)(\s*\(.+\)\s*)?\s?:\s*(.+)`  in `match` strategy.
And this will produce crash on case `label: body' due to `undefined` in second element:
![Uploading image.png…]()
