### ISSUE TITLE
[Question] support for monorepos?

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#986]
Hi @mikepenz.

I hope you find well.

I wanted to ask you if we can use the [release-changelog-builder-action](https://github.com/mikepenz/release-changelog-builder-action) to generate the changelogs in a monorepo. In this case, do you have some recommendations on what merging/rebasing strategy should use?

I have this use case:

- I am using rebasing for every new PR in the main branch. I have found a post where they mentioned that the changelog might not work when rebasing since the commits history remains linear and there are no merged PRs, so I am guessing we should use `rebase` for updating feature branching but `merging` when adding new features to the main branch.

- In the case where I have multiple tags/per module, the action will be able to pick the commits associated with each module and compute the difference between two specific tags for that specific module?

Thanks!

**Comment by mikepenz** [comment]
@dtcMLOps thanks for the ticket. 

Yes, it is possible to use the action also for mono-repos, and has been used for different such scenarios in the past.
The action includes multiple different solution to help with such usecases, one is the ability to filter tags out via the `tag_resolver` (this is an issue, but it was covered there: https://github.com/mikepenz/release-changelog-builder-action/issues/571) 

Theoretically it should also function with rebase merges - given that the action depends on 2 elements to identify which PR got merged between 2 tags (or 2 states)
- commit history between 2 tags
- `mergeSha1` hash as retrieved by PRs from the GitHub APi

As long as GitHub provides the sha1 correctly for rebase merges it should work. Given that I usually use normal merges, I have not explored that in detail though, so it would great to hear if that functions. 

Regarding the second question. Yes, PRs are filtered out as they were merged between 2 tags only, as such any merges on other branches and in other areas don't affect it. 

Furthermore you can define the categorisation more restrictive. So you could say all PRs related to 1 feature require the `feature-name` label, and categorisation label. and you use exhaustive labeling to filter them then respectively.

**Comment by mikepenz** [comment]
Well there are many different approaches how to achieve this. 

Generally the easiest may be to use different labels (and you can assign labels based on some title or so - with a different action - if you want it to be automated)

**Comment by mikepenz** [comment]
@dtcMLOps thank you very much for providing your label extracting solution, so others can find it. 

For the second part. Please open a feature request issue, as while related to mono repos I can see how that may also be beneficial for other scenarios.
