### ISSUE TITLE
[Question] set thanks to contributor on PR

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#989]
Hi @mikepenz,

Greetings.in

I have managed to set the pattern to extract merged PRs per module in my monorepo, I was wondering how can I achieve this "thanks to the contributor" that you have on your release page

![Screenshot from 2022-12-30 18-05-54](https://user-images.githubusercontent.com/115469901/210117117-e5f19dfc-f8ae-48a9-8038-02cb33f1a61f.png)

**Comment by mikepenz** [comment]
@dtcMLOps the output looks correct with `AUTHOR` - `author` being the creator of the PR. as far as I can see that's always you on the example repo. 

In the example from my repo. I do it manually there, as I don't need it to mention myself for PRs.
E.g. often a person creates an issue which I fix with the PR. and I still want to highlight appreciation - having the action to reference back to the original issue, figuring out the author is out of scope for this action, given the complexity associated with it.

**Comment by mikepenz** [comment]
@dtcMLOps indeed. You could probably achieve this using the `custom_placeholders`, with some regex which would not match in case it's your username, and will only result in the string if it is some other `AUTHOR` but that's pretty involved :D 

----

Yes, you will need to enable `fetchReleaseInformation` for this information to be fetched, given it doing 2 additional API requests it's not enabled by default. 

https://github.com/mikepenz/release-changelog-builder-action/blob/d4b41f0c90380582a0ea4898b9d7d6dd046e4801/src/releaseNotesBuilder.ts#L103-L105
