### ISSUE TITLE
[Feature request] support ${{RELEASE_DIFF}} for specific path

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#990]
Hi @mikepenz,

Hope you find well.

It would be nice if the `${{RELEASE_DIFF}}` could have support for getting the difference in a specific path since this will filter changes between 2 tags, but scoped to a folder. This will be awesome for getting the PRs commits for a monorepo where we only care about changes in a sub-project/path. 

## Issue
Currently running the `${{RELEASE_DIFF}} ` extracts the difference between the 2 tags including merged prs commits from other modules/branches.

## Aditional context
This is an example of the computed difference between 2 tags

![Screenshot from 2022-12-31 05-49-49](https://user-images.githubusercontent.com/115469901/210134028-45648721-51b6-4ae1-a4f8-6e26c64bbcdd.png)

In this example, I would like to have only 3 commits:

```bash
 - AB#000000 fix(module1): Fix 1 
 - AB#000000 fix(module1): Fix 2 
 - AB#123456 feat(module1): Add feat 1
```

**Comment by mikepenz** [comment]
@dtcMLOps I am not sure this is possible. GitHub as far as I know only has this URL to show the difference between 2 tags. 

Not sure if you have an example url which would be scoped by sub-path? 

Also the `RELEASE_DIFF` mostly generates this URL pattern, and there is no action specific logic behind

**Comment by mikepenz** [comment]
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L290-L293

**Comment by mikepenz** [comment]
These seem to be the only options sadly: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits
